### ISSUE TITLE
Time entry fields frozen in Chrome

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#10]
When using the Chrome browser to add a time block, the "OUT" and "Repeat for the next __ days" fields are frozen. Clicking with a mouse or using the tab key does not work to focus input on those fields. 

<img width="1140" alt="screen shot 2018-02-16 at 4 09 15 pm" src="https://user-images.githubusercontent.com/2225624/36329624-9b1db6b4-1334-11e8-967e-b22ad41cdd4f.png">

**Comment by adabutch** [comment]
@charlesbrandt ~ I plan to take a look at this, so I'll have more insight relatively soon ... but am noticing that these become "unfrozen" after you put a value in for the "IN."

**Comment by adabutch** [comment]
auto-focus input w.out being locked:

<img width="339" alt="screen shot 2018-06-21 at 3 42 51 pm" src="https://user-images.githubusercontent.com/2372040/41741703-dac9610e-7569-11e8-8e32-533876b00e2c.png">

**Comment by rbdietz** [comment]
Time entry needs to accommodate military time... 0900, 1600, 2300, etc





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by rbdietz** [comment]
Time entry also needs to accommodate blocks that end with midnight/2400
hours.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by adabutch** [comment]
I'll chat w. Walid about how to handle times that end on midnight/2400.

**Comment by adabutch** [comment]
I chatted w. Walid this morning, overnight checkbox handles it, I tested - looks good.

**Comment by charlesbrandt** [comment]
I've created a [separate issue for handling military time](https://github.com/City-of-Bloomington/timetrack/issues/27) (#27). Otherwise, I think this issue looks good with the latest version of timetrack.

**Comment by sibow** [comment]
this one works, I tried 2300 as IN and 2400 as out and it was reported correctly
