### ISSUE TITLE
Timecard approval

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/timetrack#101]
An option for timecard hours approval for time-entry staff:

Time entry occurs through kiosks, then with separate submission through web interface.  This would be a stripped down calendar view with submission button and comment field.  This would be somewhat similar to what IU does for approval step for kiosk staff.

At the web approval interface they would approve time and leave any comments necessary if corrections are needed such as a missed clock/out or time applied to the wrong job.

**Comment by sibow** [comment]
for clock only users the way Rick explained it is already implemented  for a different reason that they can not use timeDetails interface to add times but they can submit for approval, thanks Rick for the idea without me doing anything. I was thinking that clock users submission for approval need to be done by the automated batch that should run on last day in payperiod and we have designed a batch for that in case the employee forgot to submit. The batch process is open for discussion.

**Comment by sibow** [comment]
It is already implemented.
