### ISSUE TITLE
Redirects append extra data to URL after login

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#104]
Users are reporting difficulty logging in to the system. I think this may be a symptom of the following:

If starting at:
https://bloomington.in.gov/timetrack/

The system redirects to CAS and then back to:

https://bloomington.in.gov/timetrack/bloomington.in.gov/timetrack/timeDetails.action

If the second link is bookmarked and used outside of the local network, users are unable to access the service. (It works on the local network.)

I am unable to replicate this (even the longer version works on the external network for me), but we have had multiple reports of trouble logging in to the service. 

Cleaning this behavior up seems like a good place to start.

**Comment by sibow** [comment]
it is fixed in the new release (on outlaw right now).
