### ISSUE TITLE
Distinguish time blocks from different jobs

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#106]
Somewhat related to #59, for employees who work multiple jobs, we'll want to visually distinguish regular hours (REG) for one job from regular hours for another job.

Is the specification of which job the block is assigned to already supplied in the data from the back-end?

**Comment by sibow** [comment]
my idea is each job will have it is own calendar and need not to show on the same time details page. 
Each job will belong to a group, and each group will have a set of employee job combo. 
In the top of the calendar the user will pick the job that he/she is contributing. This will help to show the totals for each job separately.  The same will work fine for approving as each approver will approve the related employee-job.

**Comment by rbdietz** [comment]
I think this separated calendar option is worth considering.  I can think
of use cases where it would be helpful to view the separate calendars, but
also ones where it would be helpful to see all of the time blocks together
(even if this is a read-only view.) Higher up time approvers and payroll
approvers may need to review a combined view.




Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by adabutch** [comment]
Waiting to color-code multiple jobs on the calendar once we roll out the view-only for the all jobs overview.

**Comment by sibow** [comment]
implemented multiple job in time detail view when the employee select All from job list.
Daily time summary now contains all the jobs times so that employee will know his/her total hours.
Warning are changed so that it will consider all jobs such as total hours per week, etc.
Not in production yet

**Comment by adabutch** [comment]
<img width="1109" alt="screen shot 2018-12-11 at 8 52 15 am" src="https://user-images.githubusercontent.com/2372040/49805593-772e3600-fd23-11e8-8228-6cb40862d0f3.png">

**Comment by adabutch** [comment]
**note:** to finish this color coding, we just need to expose the JobID to the Pay Period Summary table below.
