### ISSUE TITLE
Approving multiple jobs

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#107]
This may be multiple separate issues, but we need to consider the workflow for time approvers to approve time for employees with multiple jobs. There are two different conditions:

- Time approver approves time for multiple jobs held by same employee. i.e. the employee reports to the same supervisor for both jobs, so the supervisor can review both sets of hours reported. Does the approval step approve both jobs separately?

- Multiple time approvers each approve different jobs held by the same employee. In this condition it could make sense for the approvers to see the hours worked in other positions, just not have the ability to approve those other jobs. Similar to reviewer for jobs not approving for?

**Comment by sibow** [comment]
the approve process is based on groups and each group will have a bunch of employee-job combo that can approve, the approver may be the same for multiple groups or different approvers for different groups.

**Comment by sibow** [comment]
implemented
