### ISSUE TITLE
Simplify path from proxied user back to timesheet approval

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#108]
As a timesheet approver, I often proxy in as users to see timesheet details. For example, clicking:

<img width="1303" alt="screen shot 2018-10-08 at 11 42 05 am" src="https://user-images.githubusercontent.com/2225624/46619157-637e0d80-caef-11e8-828a-51424fccf163.png">

Allows me to proxy as Adam. Once I've confirmed things look good, my only path out of the proxy is the User Menu -> Stop User Proxy. This takes me to my personal Time Details page. Then I click on Timesheet Approval and scroll back to my position in the list. This ends up being convoluted. 

A few different ideas: 

The Timesheet Approval navigation tab is available while I'm proxied as Adam:
<img width="1303" alt="screen shot 2018-10-08 at 11 42 56 am" src="https://user-images.githubusercontent.com/2225624/46619645-9f65a280-caf0-11e8-998f-d934b3b61763.png">
I believe this is being pulled from my settings/permissions for what tabs to show, but the action is done as Adam. Adam doesn't have this permission, so the page is blank. Maybe that could stop the user proxy and take me back to Timesheet Approval as me?

Another option or alternative is the way Kuali Time handled this scenario. (I'm unable to find a good screenshot of this since we don't have an active pay period for ITS.) It would show an "Approve" button
next to where we have "Submitted on...":

<img width="1303" alt="screen shot 2018-10-08 at 11 25 37 am" src="https://user-images.githubusercontent.com/2225624/46620441-c45b1500-caf2-11e8-8622-1d2a61241651.png">

**Comment by sibow** [comment]
implemented
