### ISSUE TITLE
Searching for division group returns error

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#109]
While trying to list all members in the Parking Garage staff group, I received the following error:

[java.sql.SQLSyntaxErrorException: Unknown column 'e.id' in 'on clause']

<img width="1295" alt="screen shot 2018-10-10 at 10 42 23 am" src="https://user-images.githubusercontent.com/2225624/46745048-4f1a4c00-cc7a-11e8-946c-c22585e35790.png">

**Comment by sibow** [comment]
fixed
