### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#11]
Clean up the jsp header to be more consistent w/ [FN1](https://github.com/City-of-Bloomington/factory-number-one).

This includes reworking the styles included to be updated to our latest, removing old/legacy references and switching our class(es) to match our current conventions.

**note:** This should also fix things like the dropdown menus, etc

**current screenshot:**
<img width="1308" alt="header-rework-v1" src="https://user-images.githubusercontent.com/2372040/40743578-eda60792-641f-11e8-9850-d3247ee79e4f.png">

**Comment by adabutch** [comment]
**current screenshot:** _(header only - don't mind the start of the calendar underneath)_
<img width="1306" alt="screen shot 2018-05-31 at 3 42 10 pm" src="https://user-images.githubusercontent.com/2372040/40804479-689e9594-64e9-11e8-8dca-5a95cc5fd6ab.png">

**Comment by adabutch** [comment]
reminder note - take a look at the fn1 kirkwood setup on the web directory

**Comment by adabutch** [comment]
I'm going to make this header more match the feel of the header on the public web directory. Ie. bigger text, bigger logo, etc ...

But, with in mind, that this will be a new starting point for FN1.

Check the files below, notice how the directory has spun off a bit compared to the latest FN1 header commit.

Current FN1 [header](https://github.com/City-of-Bloomington/factory-number-one/blob/a6bac774ef9b96b0e5a86871acedf5c491a61540/src/themes/default/includes/_header.scss) & current web directory [header](https://bloomington.in.gov/directory/css/sass-modules/layout/_header.scss) files.

**Comment by adabutch** [comment]
**Header screenshot:**
<img width="464" alt="screen shot 2018-06-01 at 10 05 06 am" src="https://user-images.githubusercontent.com/2372040/40845033-762d70fa-6583-11e8-9edd-8444e69fc1f8.png">
_**note:** Now using flex to arrange the elements, the background colors are for example purposes only to better visualize how everything's in-line (vertically center) now._

**via:** [3457a95](https://github.com/City-of-Bloomington/timetrack/commit/3457a95f1293132bc4fee450c358f6c8be817aa8)

**Comment by adabutch** [comment]
screenshot via commit [242cd77](https://github.com/City-of-Bloomington/timetrack/commit/242cd7778a265f4f1ca9c65516906649901fa34e)

<img width="1133" alt="screen shot 2018-06-01 at 10 32 20 am" src="https://user-images.githubusercontent.com/2372040/40846290-2d8a1b9c-6587-11e8-929b-3fcc1b7f1178.png">

**Comment by adabutch** [comment]
**before/after:**
<img width="496" alt="screen shot 2018-06-05 at 11 26 32 am" src="https://user-images.githubusercontent.com/2372040/40987836-91ba7570-68b7-11e8-8725-5533ce92b2a0.png">

**Before -** this is actually @sibow's OG version, not reflected in my latest commits above ... but the idea is the same for explanation.

**A -** "Settings," if your permission level enables this, you will see this nested within the same drop down. Most typical users would see this or a slight variation of it.

**B -** (A/A2 from #14) If you have proxied as another user, you will see this icon in the header navigation dropdown along w. a name change (to your name) symbolizing the action(s) you are currently engaging in.

**C -** (A/A2 from #14) This reflects who you are proxied as and gives you ability to stop acting as that user.

**Comment by charlesbrandt** [comment]
I like the layout of the new header and proxy user mechanism. Feel free to reopen if there are related issues, or we can log those separately.
