### ISSUE TITLE
repeater functionality

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#110]
Repeater doesn't work properly when setting repeat day amount via editing a time block (or if the time block only has one time eg. Time In).

When creating a new time block, repeater does work as expected.

**Comment by sibow** [comment]
we are going to change the repeater to date range, we have another issue related to this. I do not think we should use repeater for Clock-In only entries.

**Comment by sibow** [comment]
changed to date range, this issue is not relevant any more.
