### ISSUE TITLE
date field style

### ISSUE THREAD

**Issue by sibow** [City-of-Bloomington/timetrack#111]
date field need to be no more than 10 characters and these have class="date", this is needed on time block for date range and many internal pages that have start date, expire date, etc. Please Adam could you take care of this.

**Comment by adabutch** [comment]
Sadly, the HTML5 date picker isn't supported on [Safari](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Browser_compatibility).

Will continue to use this jQuery implementation already in place till our next major version rework.

**Comment by adabutch** [comment]
@sibow - this is ready for you now, let me know if you have questions/concerns 😄
