### ISSUE TITLE
"On Call 35" earn code is inflating Pay Period Summary

### ISSUE THREAD

**Issue by schertza** [City-of-Bloomington/timetrack#114]
Currently we have an earn code that we use on a given date to imply the employee should be reimbursed for being "On Call".

When you use this earn code there is a number of hours field.  What ever number you enter in this field, the value is included on the "Pay Period Summary" (weekly view)

Please consider: 
1. ignoring the value of this earn code when building the summary.

2. if a value is required, maybe accepting 0. but included the needed value when building the import file for timewarp

3. Not having the field even as data entry item for the earncode for it just needs to reside on the given date as a "flag"

**Comment by sibow** [comment]
modified to take care if the issue.
