### ISSUE TITLE
a change to the calulation driving the "Warning! Week N total hours are less than 40 hrs"

### ISSUE THREAD

**Issue by schertza** [City-of-Bloomington/timetrack#116]
Some employees have a scheduled work week less than 40 hours.

TimeTrack does hold the number of hours per week on the job.

Consider issuing the warning only when hours worked are less that Weekly Reg Hours.

Currently people who are scheduled to work 35/week are receiving a warning that they have not hit their 40 hours for that week.

**Comment by sibow** [comment]
I would like to have an example where employee weekly hours are 35, I know somebody in legal but I do not know anybody else.

**Comment by sibow** [comment]
implemented
