### ISSUE TITLE
Rework tabs

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#12]
Previously known as, 'nav1,' I'll refer to this area as, 'tabs.'

Things are pretty inconsistent at the moment, so much that it may be easier to recreate. This will likely set us up for better future componentization / modularity when I look to update FN1 down the road.

This issue is to fix up these tabs to broken out of the actual `header` markup, update the classes & fix the styles as desired. Tabs should not be related to the header styles/markup. Tabs should control which content is being shown in their respective tab content areas.

After this, and into the future (for FN1), the idea is you should be able to use tabs wherever seen fit, not solely just below the header navigation bar.

**current screenshot:**
<img width="934" alt="screen shot 2018-05-31 at 3 30 54 pm" src="https://user-images.githubusercontent.com/2372040/40805855-a1c2ad0c-64ed-11e8-9ef8-0bf535a36203.png">

**Comment by adabutch** [comment]
screenshot via [7049797](https://github.com/City-of-Bloomington/timetrack/commit/70497972e7c62bfd680e84d5070ffc7d98acac82)
<img width="903" alt="screen shot 2018-06-01 at 12 05 57 pm" src="https://user-images.githubusercontent.com/2372040/40851063-37c967b8-6594-11e8-9ad4-deadefcdbef0.png">

**Comment by charlesbrandt** [comment]
The tabs interface seems clean and functional to me now.
