### ISSUE TITLE
Time Block Time In only

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#129]
Is it the case users should be able to submit an incomplete time block in the fashion of only a time in?

I remb. talk about this previously but have lost track of the desired functionality here.

@charlesbrandt thought this behavior should be allowed.

<img width="515" alt="screen shot 2018-11-14 at 8 48 53 am" src="https://user-images.githubusercontent.com/2372040/48486721-5b9a4300-e7ea-11e8-9397-152508ebe08e.png">

**Comment by charlesbrandt** [comment]
Thanks for adding this Adam. This was previously covered in #64 and desired as a feature.

**Comment by adabutch** [comment]
^^ Nice, I'm going to close this, move the image and reopen #64. Thanks!!
