### ISSUE TITLE
CSS Flex Calendar (full width)

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#13]
Consider using css/flex + new markup for the calendar instead of using a table.

Flex would allow much more control over the styles and also enhance the ux. This comes as we've run into current issues w. cell click ability, daily logged time, etc ...

First things first, let's break this out and use an include to keep our markup for this section a little more tamed. :]

**current (old) calendar:**
<img width="913" alt="screen shot 2018-06-01 at 2 35 52 pm" src="https://user-images.githubusercontent.com/2372040/40857433-260ab2ec-65a9-11e8-866b-029cabfaa221.png">

**Comment by adabutch** [comment]
**screenshot via:** [d86d4fb](https://github.com/City-of-Bloomington/timetrack/commit/d86d4fbd101418b3f4e6472053bebd5a21fd75e4) ... styles are getting generically close, things are shaping up well - this will be nice!

<img width="1133" alt="screen shot 2018-06-01 at 4 23 55 pm" src="https://user-images.githubusercontent.com/2372040/40861844-7e12ac38-65b8-11e8-83d4-23faaa832436.png">

**Comment by adabutch** [comment]
screenshot via [b66a7db](https://github.com/City-of-Bloomington/timetrack/commit/b66a7db40fe0b48ef7d7701972612659f94117c0)

<img width="1119" alt="screen shot 2018-06-04 at 1 29 13 pm" src="https://user-images.githubusercontent.com/2372040/40932395-30c196e2-67fc-11e8-916f-112513358452.png">

**Comment by charlesbrandt** [comment]
Looks like the calendar layout fills the available area nicely now.
