### ISSUE TITLE
Time Clock - Unidentified clock in

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#130]
If a clock in action happens from a user/id that is not in the system:
- [ ] the submission should stop
- [ ] the interface should present a message, instead of presenting the current screen below

<img width="997" alt="screen shot 2018-11-14 at 8 59 10 am" src="https://user-images.githubusercontent.com/2372040/48487310-d6b02900-e7eb-11e8-87c0-95cc3c49bf6f.png">
@sibow can we accomplish this? 😄thanks!

**Comment by sibow** [comment]
added an error message that says that the ID is unrecognized.
