### ISSUE TITLE
Rolling window for default pay period in Timesheet Approval and Payroll Approval

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#131]
Currently, when selecting Timesheet Approval or Payroll Approval sections, it defaults to the previous pay period:
<img width="1295" alt="screen shot 2018-11-15 at 9 43 38 am" src="https://user-images.githubusercontent.com/2225624/48560319-8d2f0f00-e8bb-11e8-8963-17ce514dd1d0.png">

This is the correct behavior for the first week in a pay period. During this first week, approval for the previous pay period is completed and payroll is completed. 

However, during the second week it is more useful to see the status of the current pay period. This way managers can review timesheets as the pay period is coming to a close. I know it is possible to change the pay period selection using the highlighted drop down, but it would be nice if the system used this rolling or staggered window as the default.

**Comment by sibow** [comment]
implemented, not in production yet

**Comment by charlesbrandt** [comment]
Departments that use a time-clock require more interaction from time maintainers, and this maintenance happens on the current pay period. The delay in shifting to the current pay period as the default selected value requires extra clicks to change. 

Users are requesting a change for when the transition of the default pay period value happens. Currently this shift happens on the second Monday of a pay period. Users would prefer this to happen on the first Wednesday of the new pay period. This still gives time approvers and payroll processors the chance to finalize the previous pay period on the first Monday and Tuesday.

**Comment by sibow** [comment]
it is implemented
