### ISSUE TITLE
add holiday to an accrual earn code

### ISSUE THREAD

**Issue by schertza** [City-of-Bloomington/timetrack#135]
Some employees are not scheduled to work on a city Holiday.

When this happens they employee has the choice of receiving pay for the holiday (by the Holiday1.0 earn code) or they also are entitled to "bank" the holiday. so we need a "Holiday that leads to Accrual" earn code.  This currently applies to the Utilities Communications group but there also could be others.

**Comment by sibow** [comment]
added, these holiday hour codes will be accepted only in holidays

**Comment by sibow** [comment]
completed
