### ISSUE TITLE
auto gererate "unauthorized unpaid" earn code

### ISSUE THREAD

**Issue by schertza** [City-of-Bloomington/timetrack#136]
For union employees on a daily basis, and possibly "exempt/non-exempt" employees on a weekly basis, add an "unauthorized unpaid" earn code for any hours that do not match the scheduled orders.

The driving force for this was brought up while Angie was time maintaining and noticed a union employee who was late for a shift.  The union contract states that a union employee cannot "flex" their time. so we need this earn code to "add up" to their 8 or 40 hour shift.

Kelly agrees that this is needed to track "late-ness"

**Comment by sibow** [comment]
is the code UU ?

**Comment by sibow** [comment]
I added both UU and UU-T to hour code list
