### ISSUE TITLE
Users with submitted timesheet showing in "Time not submitted" section

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#137]
This may already be fixed in test, but who have already submitted timesheets are showing up in the "Time not submitted" section:

<img width="1295" alt="screen shot 2018-11-19 at 10 00 15 am" src="https://user-images.githubusercontent.com/2225624/48715416-f4fa9800-ebe2-11e8-9578-979d719ba301.png">

**Comment by adabutch** [comment]
@rbdietz dropped off a paper outlining a similar but different issue for `time not approved` ... these might be connected, we will stay tuned

**Comment by sibow** [comment]
fixed in this release

**Comment by charlesbrandt** [comment]
Looks like this issue is still showing up in production.

**Comment by charlesbrandt** [comment]
If this is difficult to fix, would it be possible to comment out this functionality so that it doesn't display to end users until we are able to fix it? Currently it is misinforming approvers that employee's time is not submitted, when in fact it has been submitted.

**Comment by charlesbrandt** [comment]
It looks like this issue was fixed in the last two weeks. I had not submitted my timesheet and my name showed in the "Time not submitted" section for Rick. No one else showed up. This is the behavior that was expected. Thanks for the fix!
