### ISSUE TITLE
Some union employees are allowed to bank more than 10 hours of comp-time earned

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#140]
Timetrack shows a warning if users are holding a bank of comp-time earned hours that is greater than 10. Some union employees are allowed to hold up to 40 hours of comp-time. This warning does not apply to them and should be changed / configurable based on the number of hours that they are allowed to bank.

**Comment by sibow** [comment]
this is changed to 40 for union employees.
