### ISSUE TITLE
Too many database connections crash

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/timetrack#142]
The web app is using up hundreds of database connections and crashing the server.   Right now, every bean and list class method generates a seperate connection.  We need to refactor the code to use only a small number of database connections for the instance.

We should try to get a database connection in the Action classes, then use that connection for all bean and list classes.

**Comment by sibow** [comment]
fixed by using one connection per request using request listener to handle closing connection when not needed any more
