### ISSUE TITLE
If a badge is not reconnized, display badge number

### ISSUE THREAD

**Issue by schertza** [City-of-Bloomington/timetrack#143]
When "badging in" (or out), and the rfid number is not found in the user database, please display the RFID number on response screen. (maybe on the same line where a name would be displayed, for that is where most are looking for a valid response.)

This RFID number that was read from the card might be different than the number that is printed on the card. Displaying what value was read from the card could help resolve these issues.

**Comment by adabutch** [comment]
@sibow - I'm happy to get this in place visually if you can perform the RFID check.

**Comment by sibow** [comment]
it is implemented now
