### ISSUE TITLE
Change warning text...

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/timetrack#144]
Per HR we should change this message 

Warning! Your HCUA: Holiday Comp Time Accrued balance is 12.04 and currently exceeds the city target balance. Please use Comp Time Accrued instead of PTO until this balance is reduced to no more than 10 hours.

to this...

Warning! Your HCUA: Holiday Comp Time Accrued balance is 12.04 and currently exceeds the city target balance. Please use Comp Time Accrued instead of PTO or Sick Time until this balance is reduced to no more than 10 hours.

**Comment by sibow** [comment]
modified on the test server
