### ISSUE TITLE
Implement Shifts

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#146]
We're starting to see situations where the concept of a shift would be useful. Not all employees at the city work a normal 8 hour shift (which is our current default). We have employees who work 12 hour or 24 hour shifts. If these employees work beyond their shift, there may be rules that allow them to earn overtime (either time accrued or compensatory). However, we can no longer assume that this shift will be fixed at 8 hours.

**Comment by sibow** [comment]
already done.
