### ISSUE TITLE
Clock-in window of time

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#147]
Some departments use the concept of a clock-in window for the start time. As an example, if a shift starts at 8am, employees can clock-in 15 minutes before their shift starts and their start time will automatically round up to 8am. 

This is different than rounding time. Any time logged after the start time should stay as is so that supervisors can respond as needed. 

Also, no rounding is required for the end of a shift. 

This will depend on shifts (#146). 

Current target groups include Utilities operations / plants (Dillman, Blucher, and Monroe).

**Comment by charlesbrandt** [comment]
After a previous discussion, we're thinking that Groups would be the right level to associate a shift.

**Comment by charlesbrandt** [comment]
This behavior is desired on clock based clock-in events. Web-based calendar entry should not be affected by this rule to preserve flexibility for time maintainers. The original entry should be logged in the Time Log History. The subsequent automated rounding action should also be logged (e.g. "Start Window").

**Comment by charlesbrandt** [comment]
Utilities T&D group would also like to use this feature, and has stated that they would like the start window to be 30 minutes before the shift starts.

**Comment by sibow** [comment]
this part of shifts as well. Time to create these shifts and assign to groups.

**Comment by sibow** [comment]
implemented
