### ISSUE TITLE
Time rounding

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#148]
Some departments are requesting automated time rounding. This is different than a clock-in window of time (#147). 

With time rounding, clock-in and clock-out events will be rounded up **or** down based on where they fall in the increments. The amount of time to round should likely be configurable. Some examples could be 6 minute increments and 15 minute increments. :00 should always be the starting point. Rounding direction should change half way between increments. 

Parks & Recreation are an example of a department that would like to use rounding.

**Comment by charlesbrandt** [comment]
This behavior is desired on clock-in and clock-out events. Web-based calendar entry should not be affected by this rule to preserve flexibility for time maintainers. The original entry should be logged in the Time Log History. The subsequent automated rounding action should also be logged (e.g. "Auto-rounding").

**Comment by sibow** [comment]
this is part of shift configuration, we need to add shifts probably multiple ones and then assigning the group to a shift.
