### ISSUE TITLE
Configurable default for overtime handling by group

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#149]
Currently when employees earn overtime, the system assumes they will accrue time in the comp-time earned bank. For some departments and divisions, the default is to earn monetary compensation for the extra time. This is creating a lot of extra work for time maintainers in these departments; they have to manually adjust each instance. 

Having the ability to adjust the default method for handling overtime on a group by group basis would address this issue.

**Comment by sibow** [comment]
I added default_earn_code parameter to groups so that each group can be configured differently.
The default is 'Comp Time' ie hours and the other option is 'Over Time' which  is money.
I removed this parameter from shifts because not every group has shifts.
