### ISSUE TITLE
Calendar Holidays

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#15]
The calendar should display the name of a holiday, if there is a holiday for any given day.

<img width="316" alt="screen shot 2018-06-05 at 3 39 30 pm" src="https://user-images.githubusercontent.com/2372040/40999089-dbc52c30-68d7-11e8-8bd8-220b7913f50c.png">

**note:** styles are generically in place to handle this, but the example in the markup is solely static.

cc // @sibow ( calendarFullNew.jsp )

**Comment by rbdietz** [comment]
Only "city holidays" are relevant for payroll purposes.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
See also #24, #25, #26

**Comment by adabutch** [comment]
closed via [35cdaeb](https://github.com/City-of-Bloomington/timetrack/commit/35cdaeb64a1c63dfe9f62ea369489d3405fed2d1)
