### ISSUE TITLE
Logging out should also log out of CAS session

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#150]
After some discussion and feedback, we're planning to change functionality for the "Logout" button. Currently it only removes the session for Timetrack specifically. However, with an active CAS session the user can instantly, seamlessly initiate a new session so it appears that the logout action never happened. 

Logging out through CAS will have the side effect that the user will also be logged out of all active sessions for other applications that rely on CAS (e.g. email). This seems like a better default action if a user goes through the effort of clicking "Logout". Maintaining an active CAS session is still possible by not choosing "Logout".

**Comment by sibow** [comment]
done
