### ISSUE TITLE
comp time earned during payperiod some employees want to use

### ISSUE THREAD

**Issue by sibow** [City-of-Bloomington/timetrack#157]
comp time earned during payperiod some employees want to use

**Comment by charlesbrandt** [comment]
We should confirm with HR that this behavior should be allowed before implementing this. It may be possible for us to calculate these available comp time hours in real time, but HR currently prefers that these are processed via payroll / approvers / the financial management system first

**Comment by charlesbrandt** [comment]
Kelly sent a request for this feature today from the Controller's Office:

> We have some employees, especially union, that earn comp time early in the week and then want to use it later in the week.  Of course Time Track does not recognize the comp time earned earlier in the week.  Is there a way Time Track can update the comp time accrual every day so employees can use it in the same pay period?

**Comment by sibow** [comment]
I created a csv file with two earn codes CU (comp used) and CE1.5 (comp earned) for employees who do not have any comp accrual or very little to find out if new world will allow to used earned accrual during the pay period. Asked Kelly to test
the file and she said it did work.

**Comment by charlesbrandt** [comment]
Before we enable this feature in a production version of Timetrack, we will need to confirm with HR that this is desired behavior.

**Comment by sibow** [comment]
It looks like HR are not OK with this feature, it may also causes other problems when
an employee uses comp time earned where the approve does not approve and at the same time the employee used comp time used.
So we are keeping this feature on hold till we get an approve approach to implement.

**Comment by sibow** [comment]
We shelf this issue now till we HR tells us otherwise.
