### ISSUE TITLE
Pay Period Selects

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#16]
The pay period option select should only show applicable ranges in which there was employment?

For example, if I started 05/21/2018 and today is 06/05/2018 ... I should only see pay period ranges from that point forward?

This is definitely open to discussion!

<img width="695" alt="screen shot 2018-06-05 at 4 23 19 pm" src="https://user-images.githubusercontent.com/2372040/41000723-e24c4d22-68dc-11e8-8263-69e4566ddd48.png">

**Comment by rbdietz** [comment]
I think it makes sense to limit the options to populated pay periods.  

Even so, at some point the dropdown will get excessively long. It may make sense to limit the options in the pulldown, but provide another method to access pay-periods older than, say, 3 months back.

**Comment by sibow** [comment]
time off will be part of leave management, that may take place in next major upgrade.

**Comment by sibow** [comment]
greater than 3 month back implemented
