### ISSUE TITLE
Clock-out window of time

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#164]
This is similar to #147, but should apply to the end of the shift. In this case, any time within the window **after** the shift ends should be automatically rounded down to the end of the shift. 

Example:  
If a shift ends at 5pm and has a 15 minute clock-out window, a badge-out action at 5:14pm should be rounded back to 5pm.

**Comment by sibow** [comment]
would the start window and end window be the same or we need to have different windows?

**Comment by rbdietz** [comment]
There needs to be different/independent windows for start and end.

**Comment by sibow** [comment]
added
