### ISSUE TITLE
Include "To:" in reminder emails

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#165]
The "To:" field in the reminder emails generated by Timetrack is not being specified. 

<img width="947" alt="screen shot 2018-12-31 at 11 37 55 am" src="https://user-images.githubusercontent.com/2225624/50564204-204bc900-0cf1-11e9-8221-2e6752aaf846.png">

This is an important detail to include. Some users are reporting that they've received a reminder email after having submitted their timesheet. It could be that the reminder was for a different employee. This scenario could happen if a different employee stops working at the city, their email address may be configured as an alias on a manager's email account. Without the "To:" being populated, we will not be able to troubleshoot why users are receiving the email reminder. 

This is related to functionality discussed in #103.

**Comment by adabutch** [comment]
@rbdietz received two of these email reminders, lets also check into that while in this issue. 

Paper example on my desk.

**Comment by sibow** [comment]
I disabled this feature now since I do not have enough enough to debug. Because email is sensitive issue and the only way to test is to send emails which is annoying to people. 
I will revisit this issue in the future.

**Comment by rbdietz** [comment]
I don’t think this needs to be disabled. It’s better to have the reminder than not i think.

**Comment by charlesbrandt** [comment]
The "To:" field was filled in on this period's reminders so this issue is fixed. We're still having the issue of reminders being sent to those who have submitted (#103), but that issue is still open.
