### ISSUE TITLE
Timeclock not working on Saturday evening / Sundays

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#169]
As the system is being deployed more widely, we're hearing reports that timeclocks are non-responsive on Saturday evenings through Sunday. This past weekend (between 12/29/2018 and 12/30/2018) we received reports from both Frank Southern and Utilities T&D. Frank Southern shared a picture of what the timeclock looked like after a badge submission:

![img_1603](https://user-images.githubusercontent.com/2225624/50594153-675cca00-0e69-11e9-9372-cda6ff3b4c6a.jpg)

Frank Southern also tried restarting the device (unplugged the power, waited approximately 30 seconds, then plugged back in). The clock came back up and showed the standard screen, so we know the server was responding.

On Monday, the clocks started working again. In this case, it was the end of a pay period.. maybe this is something related to timesheet initialization?

**Comment by charlesbrandt** [comment]
This happened again yesterday. The issue does seem to be in sync with the payroll cycle. Frank Southern and Street both reported the service was not available, so it is not limited to one location. 
![img_1613](https://user-images.githubusercontent.com/2225624/51126159-70965100-17f0-11e9-8140-90daacd5e6c7.JPG)

**Comment by sibow** [comment]
I added more log statement where I expect the exception happen, I modified database connection testing which I think is the most probable reason. Wait for the next weekend for next real test

**Comment by charlesbrandt** [comment]
This issue happened again yesterday at Frank Southern.

**Comment by charlesbrandt** [comment]
I didn't hear any reports of this issue yesterday. That would have been the day it was showing up previously. Calling this one fixed. Thanks Walid!
