### ISSUE TITLE
Calendar Log Summaries (below calendar)

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#17]
Begin cleaning up the sections beneath the calendar.

For generic before reference, this screenshot below is what's current.

<img width="935" alt="screen shot 2018-06-06 at 12 29 18 pm" src="https://user-images.githubusercontent.com/2372040/41052275-5b8e8f48-6986-11e8-8c8c-7b9945afeb6f.png">

**Comment by adabutch** [comment]
Screenshot below shows the entire homepage of TimeTrack, but we are really only focusing on the bottom area (below the calendar) within this issue. 

I included the entire page to better sense how things are laid out in respect to each other.

![timetrack copy](https://user-images.githubusercontent.com/2372040/41171066-28d22fa4-6b1d-11e8-8a2f-3e16f9667dd2.jpg)

**Comment by charlesbrandt** [comment]
This looks great!

**Comment by rbdietz** [comment]
Looking good, thanks!  We need to figure out how to include our timekeeping
error alerts (current in Timewarp) on this display.  These need to either
be corrected or acknowledged before submission happens.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov
