### ISSUE TITLE
Enable links to employees in Time Not Submitted section

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#173]
On the Timesheet Approval page it would be helpful to link to employee timesheets in the header when they are listed. This is in addition to being able to access the timesheet by scrolling down on the page to the section already dedicated to that employee:

![image 9](https://user-images.githubusercontent.com/2225624/51053493-d2b04580-15a7-11e9-8d3d-77a0bc44b194.png)

**Comment by sibow** [comment]
added to approve and payroll approve page
