### ISSUE TITLE
New employee not added to group

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#174]
When creating a new employee, the group is selected, but currently it looks like the association with the group fails to complete on submit:

<img width="1295" alt="screen shot 2019-01-11 at 4 42 05 pm" src="https://user-images.githubusercontent.com/2225624/51061099-06976500-15c0-11e9-918a-707f51617d58.png">

**Comment by charlesbrandt** [comment]
A subsequent, separate action to add the employee to the correct group does complete successfully.

**Comment by sibow** [comment]
fixed
