### ISSUE TITLE
Approve Button not needed

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/timetrack#176]
Inactivate, gray out or remove "Approve" button from pages where all present employees have already been approved.  This applies to time approval and payroll approval.

![screen shot 2019-01-15 at 11 16 31 pm](https://user-images.githubusercontent.com/1135994/51226167-2ad6a700-191c-11e9-9d56-7f98338f09e7.png)

**Comment by sibow** [comment]
it is removed completely when not needed
