### ISSUE TITLE
Automatically clock-in for multiple jobs after job selection

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#178]
Users with multiple jobs need to choose which job they are clocking in to. After making their job selection, there is a "Clock in" button that must be pressed to confirm their selection. Currently, if the clock in button is not pressed the clock in action is lost. 

We want to keep the confirmation button in place to give users a chance to change their selection incase there is a mistake. However, if a job selection is made and the Clock In button is not explicitly pressed, we should still log the clock in action after the timeout expires. 

I think this could mitigate some issues where users with multiple jobs think they have clocked in but the entry is not logged. 

<img width="1316" alt="screen shot 2019-01-25 at 12 03 50 pm" src="https://user-images.githubusercontent.com/2225624/51761469-212b0d00-209b-11e9-8811-4706a344f818.png">

> In this image, if Clock In is not pressed but the timeout is reached, the clock in action should still happen.

**Comment by adabutch** [comment]
should be fixed up now via https://github.com/City-of-Bloomington/timetrack/commit/a0a7895e40348fae6ceb38df32a74a36ac0cbad6
