### ISSUE TITLE
Review badge action rules

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#179]
Timetrack has rules for clock entry to intelligently handle missed badge actions. 

For example, an employee clocks-in in the morning, forgets to clock-out, and then clocks-in again the next day. The system will treat both of the clock-in actions as clock-ins instead of making one long ~24 hour time block. It does this by setting a threshold (currently 14 hours). If the subsequent action is past the threshold, it assumes the clock-out action was skipped and starts a new block. 

We have some scenarios where employees work longer than 14 hours. In some cases, these are regular schedules that we can accommodate with shifts. In other cases, these are weather related tasks that cannot be planned or scheduled for. In those cases, a time maintainer is required to go back and combine the two clock-in actions into a single time block. 

It would be good to start logging or collecting the number of times this condition is met. This would help us analyze which case saves more time for time maintainers.

**Comment by sibow** [comment]
time maintainers and approvers are currently handling missed clock-out, I don't think we need to worry about this right now.
