### ISSUE TITLE
Internal Pages

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#18]
The internal pages need just a splash of polish before they are sync'd w/ the look/feel of the homepage. 

Here is where they'll be updated.

**Comment by adabutch** [comment]
internal settings page (before vs after) via [8164702](https://github.com/City-of-Bloomington/timetrack/commit/81647020c556e458feaae5ed83e19503c925b25b):

![settings](https://user-images.githubusercontent.com/2372040/41175734-019291a4-6b2c-11e8-91a4-3caf3925f5af.png)

**Comment by adabutch** [comment]
**note:** the tabs above the internal page content need to feature an active class to indicate if you are on the page. 

ie. on this page the "Settings" tab above would be a darker blue, as seen on the, "Time Details."

**Comment by adabutch** [comment]
**Timesheet Approval** - internal page, before vs. after via [1116109](https://github.com/City-of-Bloomington/timetrack/commit/11161095c2728642fe23f0b52228bca604af9764):

![timesheet approval - before vs after](https://user-images.githubusercontent.com/2372040/41255822-d2cbffc4-6d95-11e8-9419-63765eac44c0.jpg)

**Comment by rbdietz** [comment]
You will need to accommodate individual approval and an "approve all"
option on this page.

You should also think about how "timewarp" style error reporting can be
incorporated so approvers can see any identified errors and warnings before
approval.

Walid can provide the warning/error list from Timewarp.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by adabutch** [comment]
**Payroll Process Approval** - internal page, before vs. after via [b89a22d](https://github.com/City-of-Bloomington/timetrack/commit/b89a22d56759391b0ebef672842df92b61376ebf)

![payroll approval - before vs after-01](https://user-images.githubusercontent.com/2372040/41295593-f1811092-6e28-11e8-8a0b-e7ed3de3187d.jpg)

**Note:** The payroll process approve checkboxes are for example placeholding. As @rbdietz points out, we will need an "approval all" checkbox option. Does that only show when there is more than one person to be approved? Also - I've got warnings/errors styled, just need to apply to such. Thanks!

**Comment by adabutch** [comment]
Example message/error placement.

**note:** The errors aren't firing on the approve/process pages, but the style is in place. We also need the ability to color code these messages based on type of message being displayed?

<img width="1071" alt="screen shot 2018-06-12 at 10 55 49 am" src="https://user-images.githubusercontent.com/2372040/41298769-fbc35838-6e2f-11e8-9637-bf6e3edfc233.png">

**Comment by rbdietz** [comment]
There are many different errors/warnings.... missing 40 hours, not enough
benefit time, excessive benefit time, incorrect increment for PTO, etc.  I
don't think there needs to be different colors right now.  But there can be
multiple warnings per person so the warning area should be able to
accommodate multiple items.

This type of warning block should also be present on the individual time
entry/submission page.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by adabutch** [comment]
**note:** Data entry & Timewarp settings pages are still to-do

**Comment by sibow** [comment]
time approvers and payroll processer can see the warning now

**Comment by charlesbrandt** [comment]
Internal settings pages could use another round of polish, but those tasks can be broken up into separate specific issue requests. This is good enough for now. Thanks for posting befores and afters!
