### ISSUE TITLE
rebuild timewarp to place exported hours on days worked

### ISSUE THREAD

**Issue by schertza** [City-of-Bloomington/timetrack#186]
This is a major change.

I'm just outlining it in this issue.

The concept of this issue is build time blocks for import on the days that the work was done instead of the last day of the payperiod.

Some of the items to consider are:

still have employee enter hours worked.

build a secondary data structure that uses cob rules to overlay the hours worked vs hours entered into new world.

example working accross the week we would create reg hours in the new datastructure entered as reg upto 40. Once the total of 40 hours is reached, we then start using the next earn code defined by the grade and status. (possibly Professional hours or OT1.5, CU1.5, etc)

We then export from this data structure for each of the days a person worked.  New World Payroll does pay attention to the date so that we can easily reimburse them the correct amount they deserve.

We would also need to pay attention to grade and status per date as well. We can select this information from new world.

Many things to work out on this....

**Comment by sibow** [comment]
is there any reason we should do that, just asking?
