### ISSUE TITLE
Unable to assign group

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#187]
When trying to add an employee to a group:
https://bloomington.in.gov/timetrack/employee.action?id=19

I receive the following stacktrace:

> 
> Messages: | tag 'select', field 'list', name 'groupEmployee.group_id': The requested list key 'groups' could not be resolved as a collection/array/map/enumeration/iterator type. Example: people or people.{name}tag 'select', field 'list', name 'groupEmployee.group_id': The requested list key 'groups' could not be resolved as a collection/array/map/enumeration/iterator type. Example: people or people.{name} - [unknown location]
> -- | --
> File: | org/apache/jasper/servlet/JspServletWrapper.java
> Line number: | 601
> 
> Stacktraces
> org.apache.jasper.JasperException: tag 'select', field 'list', name 'groupEmployee.group_id': The requested list key 'groups' could not be resolved as a collection/array/map/enumeration/iterator type. Example: people or people.{name} - [unknown location]
>     org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:601)
>     org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:481)
>     org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
>     org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
>     javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
>     org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
>     org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>     org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
>     org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>     org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>     in.bloomington.timer.util.LoginFilter.doFilter(LoginFilter.java:55)
>     org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>     org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>     org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
>     org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:467)
>     org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:392)
>     org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:311)
>     org.apache.struts2.result.ServletDispatcherResult.doExecute(ServletDispatcherResult.java:169)
>     org.apache.struts2.result.StrutsResultSupport.execute(StrutsResultSupport.java:206)
>     com.opensymphony.xwork2.DefaultActionInvocation.executeResult(DefaultActionInvocation.java:375)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:279)
>     org.apache.struts2.interceptor.debugging.DebuggingInterceptor.intercept(DebuggingInterceptor.java:250)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:179)
>     com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:263)
>     org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:49)
>     com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.doIntercept(ConversionErrorInterceptor.java:142)
>     com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:137)
>     com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:137)
>     com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.StaticParametersInterceptor.intercept(StaticParametersInterceptor.java:201)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:67)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     org.apache.struts2.interceptor.DateTextFieldInterceptor.intercept(DateTextFieldInterceptor.java:133)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:89)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     org.apache.struts2.interceptor.FileUploadInterceptor.intercept(FileUploadInterceptor.java:243)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.ModelDrivenInterceptor.intercept(ModelDrivenInterceptor.java:101)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.ScopedModelDrivenInterceptor.intercept(ScopedModelDrivenInterceptor.java:142)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.ChainingInterceptor.intercept(ChainingInterceptor.java:160)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:175)
>     com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     org.apache.struts2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:121)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:167)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.AliasInterceptor.intercept(AliasInterceptor.java:203)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:196)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:48)
>     org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:574)
>     org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79)
>     org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:141)
>     org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>     org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>     org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
>     org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
>     org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
>     org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
>     org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
>     org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
>     org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
>     org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
>     org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:486)
>     org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
>     org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
>     org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
>     org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
>     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>     org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>     java.lang.Thread.run(Thread.java:748)
>     
> tag 'select', field 'list', name 'groupEmployee.group_id': The requested list key 'groups' could not be resolved as a collection/array/map/enumeration/iterator type. Example: people or people.{name} - [unknown location]
>     org.apache.struts2.components.Component.fieldError(Component.java:257)
>     org.apache.struts2.components.Component.findValue(Component.java:353)
>     org.apache.struts2.components.ListUIBean.evaluateExtraParams(ListUIBean.java:81)
>     org.apache.struts2.components.Select.evaluateExtraParams(Select.java:101)
>     org.apache.struts2.components.UIBean.evaluateParams(UIBean.java:884)
>     org.apache.struts2.components.UIBean.end(UIBean.java:533)
>     org.apache.struts2.views.jsp.ComponentTagSupport.doEndTag(ComponentTagSupport.java:39)
>     org.apache.jsp.WEB_002dINF.jsp.groupEmployee_jsp._jspx_meth_s_005fselect_005f0(groupEmployee_jsp.java:2455)
>     org.apache.jsp.WEB_002dINF.jsp.groupEmployee_jsp._jspx_meth_s_005felse_005f2(groupEmployee_jsp.java:2407)
>     org.apache.jsp.WEB_002dINF.jsp.groupEmployee_jsp._jspx_meth_s_005fform_005f0(groupEmployee_jsp.java:1815)
>     org.apache.jsp.WEB_002dINF.jsp.groupEmployee_jsp._jspService(groupEmployee_jsp.java:250)
>     org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
>     javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
>     org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
>     org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
>     org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
>     javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
>     org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
>     org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>     org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
>     org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>     org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>     in.bloomington.timer.util.LoginFilter.doFilter(LoginFilter.java:55)
>     org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>     org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>     org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
>     org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:467)
>     org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:392)
>     org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:311)
>     org.apache.struts2.result.ServletDispatcherResult.doExecute(ServletDispatcherResult.java:169)
>     org.apache.struts2.result.StrutsResultSupport.execute(StrutsResultSupport.java:206)
>     com.opensymphony.xwork2.DefaultActionInvocation.executeResult(DefaultActionInvocation.java:375)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:279)
>     org.apache.struts2.interceptor.debugging.DebuggingInterceptor.intercept(DebuggingInterceptor.java:250)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:179)
>     com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:263)
>     org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:49)
>     com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.doIntercept(ConversionErrorInterceptor.java:142)
>     com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:137)
>     com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:137)
>     com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.StaticParametersInterceptor.intercept(StaticParametersInterceptor.java:201)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:67)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     org.apache.struts2.interceptor.DateTextFieldInterceptor.intercept(DateTextFieldInterceptor.java:133)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:89)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     org.apache.struts2.interceptor.FileUploadInterceptor.intercept(FileUploadInterceptor.java:243)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.ModelDrivenInterceptor.intercept(ModelDrivenInterceptor.java:101)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.ScopedModelDrivenInterceptor.intercept(ScopedModelDrivenInterceptor.java:142)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.ChainingInterceptor.intercept(ChainingInterceptor.java:160)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:175)
>     com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     org.apache.struts2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:121)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:167)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.AliasInterceptor.intercept(AliasInterceptor.java:203)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:196)
>     com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249)
>     org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:48)
>     org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:574)
>     org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79)
>     org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:141)
>     org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>     org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>     org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
>     org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
>     org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
>     org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
>     org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
>     org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
>     org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
>     org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
>     org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:486)
>     org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
>     org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
>     org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
>     org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
>     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>     org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>     java.lang.Thread.run(Thread.java:748)
> 
>

**Comment by sibow** [comment]
this is because we do not have any group for the Office of the Mayer. She is in Kuali

**Comment by charlesbrandt** [comment]
Ah, that explains the error. Soon (TBD) we will be bringing Office of the Mayor on to the Timetrack system. We'll want to make sure all groups and accounts that are currently configured in Kuali are mirrored in Timetrack.

**Comment by charlesbrandt** [comment]
I created a group, but I am unable to add her to the group.

**Comment by sibow** [comment]
fixed but not in production yet, till  tomorrow.
