### ISSUE TITLE
Clock-in Sunday and Clock-out Monday fails at end of pay period

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#188]
This may be related to #169, but I think it's a separate issue. We had a report from FSC that employees who clocked in on Sunday (2/10) and worked overnight were unable to clock out Monday morning (2/11). That would have spanned two pay periods. Could we try a similar troubleshooting approach as #169 and set up a pay period on the test server to replicate this?

**Comment by sibow** [comment]
modified the code but not tested yet.

**Comment by sibow** [comment]
it is tested and it is working, will keep open till next last Sunday in pay period

**Comment by sibow** [comment]
I checked a number of employee who work overnight and they had clock in and out without a problem.
