### ISSUE TITLE
no confirmation on delete of time block

### ISSUE THREAD

**Issue by schertza** [City-of-Bloomington/timetrack#19]
no confirmation on delete of time block. I personally think it is needed, but also up for suggestions

**Comment by adabutch** [comment]
This is a good suggestion! One we've been discussing for a bit actually & feel is def. needed.

The idea is, when you click the 'X' to remove a logged time slot, you should be prompted to confirm the action was actually desired.

**Comment by charlesbrandt** [comment]
Looks like the confirmation was added by Adam.
