### ISSUE TITLE
Department shifts and employees

### ISSUE THREAD

**Issue by sibow** [City-of-Bloomington/timetrack#191]
To simplify adding time blocks for certain department such as Fire and Police, here is my suggestions:
1-Create Department Shifts where employees in such department will be assigned, we will end up with
couple of these shift per department.
Employees can be added or removed as needed.
2-For each shift mentioned above will provide an interface to set the following values:
   a-Daily start time and end time.
   b-a list of dates for the shift
   c-Save where each employee will be assign these dates and time

Benefit of this will be less labor and faster to process.
Any suggestions?

**Comment by charlesbrandt** [comment]
Would a shift be applied to a group? I'd have some concerns if we have to maintain membership to the group and the shift separately, but maybe there are cases when that makes sense?

Otherwise this sounds like a good plan.

**Comment by sibow** [comment]
we may use group id in the shift so that we do not need to add employees one by one, we need to check with Bernice about that

**Comment by sibow** [comment]
we do not need shift just group, we need default hour code, start time, end time and dates list.

**Comment by sibow** [comment]
completed
