### ISSUE TITLE
Add fields for Parks Employees and Jobs Report

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#194]
The following fields would be useful in addition to the existing fields for each position:

- employee new world number
- job / position start date  
- hourly wage (if it is possible to pull this information from NWS)
- blank column to indicate type of change (with examples for acceptable values?)

Additionally, the employee name should be formatted as "lastname, firstname" to facilitate easier sorting in a spreadsheet.

**Comment by sibow** [comment]
completed
