### ISSUE TITLE
manager service given group

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#195]
@sibow - possible to return manager data from a select group?

**For example:** 
consider the below, given a select group ... return the manager data of the group?

**request:** 
`GroupManagerService?group_id=10 `

**response:**
```
{
name: "Adam Butcher"
phone: "888-888-8888"
email: "me @ us . gov"
}
```

**Comment by sibow** [comment]
completed

**Comment by adabutch** [comment]
@sibow - we need to exclude results where `workflow: "Review"`

**Comment by sibow** [comment]
excluded
