### ISSUE TITLE
Move details from timewarp to main interface

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#197]
Timewarp does calculations based on a number of rules to determine when someone works past their scheduled hours and should be compensated for those extra hours (monetarily or earns time). It would be helpful to all Timetrack users to be able to see how their current timesheet is being interpreted by Timewarp on the main time details page. This would also minimize the dependency on reviewing these details in timewarp (see also #196).

**Comment by sibow** [comment]
in the new release timewarp info will be listed on the main detail page
