### ISSUE TITLE
time block hour code capitalization

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#199]
When selecting an `Hour Code`, from within a `Time Block`, the abbreviations after they hour key should be capitalized.

@sibow - Looks like this is spit out from your end, [here](https://github.com/City-of-Bloomington/timetrack/blob/master/src/main/webapp/WEB-INF/jsp/timeBlock.jsp#L55)

**For example:**
_**Current:**_
`FMCU: Fmla compt time used`

_**Should be:**_
`FMCU: FMLA compt time used`

_**note:** see print off on my desk for more detail_

**Comment by sibow** [comment]
updated
