### ISSUE TITLE
holding state of Pay period when deleting time block

### ISSUE THREAD

**Issue by schertza** [City-of-Bloomington/timetrack#20]
I have noticed if I delete a time block from a previous pay period that has not been submitted, the page refreshes with the current payperiod.

I believe the app should hold state of the currently viewed pay period, and refresh with that same pay period if a delete or update happens.

**Comment by adabutch** [comment]
Another good suggestion!

I agree, in that I expect this same behavior as a user.

Thanks @schertza!

**Comment by adabutch** [comment]
@sibow - I think I'll need your assistance for this - when you can, thanks!

**Comment by sibow** [comment]
this is fixed
