### ISSUE TITLE
Calendar view time entry values cached in IE

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#200]
In IE, the following scenario was reported by a user:

I changed the time on one day to add a minute to my Time Out, and it took the entry on the overall page, but if you click in that specific time block, it still shows the old time.  So for 2/16/19 I changed my out time to 01:41 am and hit confirm.  The total for the week increased, and the day log shows 01:41, but if I click back into the block of time, it is still 01:40.

![image 10](https://user-images.githubusercontent.com/2225624/53518965-25828580-3aa0-11e9-9792-3a25221bb304.png)

![unnamed](https://user-images.githubusercontent.com/2225624/53518991-3501ce80-3aa0-11e9-85ce-713844aa0e9e.png)

This process seems to work just fine in other browsers.

**Comment by sibow** [comment]
according to Elaine this was happening on IE browser which we do not recommend people to use any more.

**Comment by sibow** [comment]
it could be that IE does not support certain JS related frameworks that Adam is using.
Even MS recommend people not use IE any more

**Comment by rbdietz** [comment]
Can we do a browser check and indicate IE isn't supported by Timetrack as
well as by Microsoft? E




Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0076 Cell
bloomington.in.gov

**Comment by adabutch** [comment]
I could not replicate this issue using IE 11 (Justin's computer).

Also reporting that Edge is behaving as expected, no caching happening there either.

I'm open to a browser check, but that I feel is worth a discussion and it's own issue (#202).
