### ISSUE TITLE
Handle extra hours for 12 hour shifts

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#201]
Utilities plant operators typically work 12 hour shifts. Employees work 3 days one week (3x12=36 hours) and 4 days the next week (4x12=48). 36+48=84 which results in 4 hours of overtime, every pay period. It would be nice if Timewarp could automatically catch this condition so that time approvers do not need to manually adjust all operators' times to reflect the condition.

**Comment by sibow** [comment]
According to Kelly, she goes by week total hours, so the first week in previous example will add nothing but
second week will add 8hrs of overtime or comp time.

**Comment by sibow** [comment]
the group shift that specifies the shift duration, start time took care of this.
