### ISSUE TITLE
Associate start and end times with hours only blocks

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#204]
Currently, for certain earn codes like PTO, we only record the total number of hours associated with the earn code. We do not track the start and end times for these blocks. For over-time situations, these blocks are used to designate whether an employee receives monetary compensation or earns time. This current approach of specifying the total number of hours makes it easier to split up the over-time in the way the employee requests. 

However, other departments have requested a way to know when the over-time was worked. (e.g. Animal Care and Control, Police, etc.) This approach would make the over-time allocation more complex. 

Alan has suggested moving the compensation allocation (monetary vs earn time) out of the earn code / time block. In this scenario, eligible employees could be given a slider to indicate what percentage of their over-time should be paid monetarily vs earning time. This setting could carry over from one pay period to the next, and would be available for adjustment by the employee before submitting the timesheet at the end of the pay period. 

This issue is also related to #197 -- we would need a way to display how allocations are currently configured in the main time details interface before timewarp does this calculation. 

The implementation specifics are still open for discussion.

**Comment by sibow** [comment]
added special earn codes similar to CE1.0, CE1.5, OT.10 and OT1.5 that require start time and end time
currently used by Police employees only

**Comment by sibow** [comment]
we have the new codes available for police employees only.
