### ISSUE TITLE
Adjusting time off blocks does not factor in time available in current block

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#205]
If an employee adds a time block for CUA and subsequently tries to adjust the hours value, timetrack may report an error because the remaining balance is not greater than the changed value. (i.e. the changed value is not covered by the remaining balance) In this case, timetrack should consider the amount that is also currently set in the timeblock being changed. An example scenario is currently available for review in Cass's timesheet for this pay period.

<img width="1245" alt="screen shot 2019-03-07 at 8 55 20 am" src="https://user-images.githubusercontent.com/2225624/53962598-7b1aeb80-40b9-11e9-8e39-c44448aa59ed.png">
<img width="1245" alt="screen shot 2019-03-07 at 8 56 15 am" src="https://user-images.githubusercontent.com/2225624/53962603-7fdf9f80-40b9-11e9-8c0b-ab0296e92eb8.png">
<img width="1245" alt="screen shot 2019-03-07 at 8 56 52 am" src="https://user-images.githubusercontent.com/2225624/53962610-840bbd00-40b9-11e9-9707-7eb9394e981a.png">

This may also be the case for other types of time off

**Comment by sibow** [comment]
updated on the test server. Will be available on next release
