### ISSUE TITLE
Improve example text

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/timetrack#206]
WE should adjust the default text in the time fields to be something like...

hhmm or hh:mm AM/PM
Example: 1345 or 01:45 PM

![Screen Shot 2019-03-07 at 1 51 50 AM](https://user-images.githubusercontent.com/1135994/54066524-811ae480-41ff-11e9-92ea-633f725858cf.png)

**Comment by sibow** [comment]
changed
