### ISSUE TITLE
monetary timewarp page

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#208]
Improve the data view ability of the new monetary timewarp page.

**_Current:_**
<img width="1129" alt="Screen Shot 2019-03-22 at 3 20 26 PM" src="https://user-images.githubusercontent.com/2372040/54847976-4bbdce80-4cb6-11e9-846d-5c002f5eae46.png">

**_New:_**
<img width="1098" alt="Screen Shot 2019-03-22 at 3 17 57 PM" src="https://user-images.githubusercontent.com/2372040/54847993-5a0bea80-4cb6-11e9-9895-43b0b6277be3.png">

**Comment by adabutch** [comment]
**note:** Grs = Gross

We could change if desired but I'd need to ping @sibow for the server side. Maybe it makes more sense to use "Gr" or "Gro" instead of Grs.

cc // @rbdietz via text changes request

**Comment by sibow** [comment]
changed to Gr instead of Grs
