### ISSUE TITLE
pay period notes issue

### ISSUE THREAD

**Issue by sibow** [City-of-Bloomington/timetrack#209]
This is was reported by Cas
Also, I am unable to add pay period notes reliably as sometimes it just pops up without a text box. I can submit or cancel, but there is no where to enter the text. I tried this with Chrome and Firefox with different results. Chrome was spotty and sometimes the text box would open and other times it wouldn't. Firefox did not have this problem at all.

**Comment by adabutch** [comment]
I noticed an initial FOUC but overall seemed to work via Justin's machine. I did notice the modal jump on Walid's machine. Via os x there is a brief moment of fouc but behaves as expected.

<img width="1110" alt="Screen Shot 2019-03-29 at 9 51 59 AM" src="https://user-images.githubusercontent.com/2372040/55237336-51606a80-5208-11e9-91ef-a5d4a61b0a2a.png">
