### ISSUE TITLE
Alert Messages

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#21]
Strut Action Error and Action Message's get automatically generated html.

We need to work our styles to fit their markup, so alerts are generically uniform everywhere.

We should also use a template include file for the markup that we can include on any page that needs it.

This ticket can also house alerts/messages/errors items that need attention that are not strut auto-generated. Also note, such alert messages appear in a lot of places, not just on this page ... I'm just using it for an opening example here.

**In the screenshot:**
**A:** messages auto-generated via struts
**B:** messages we have _full_ control over, note these will be moved to the top, but Walid has to redo a couple things first.

![alerts-01](https://user-images.githubusercontent.com/2372040/41309438-cb8e3422-6e4c-11e8-898c-6c2ea6b5f383.jpg)

**Comment by inghamn** [comment]
We should probably edit the code so that we have full control over all error messages.  Any generic html generated by struts is going to look weird.

**Comment by sibow** [comment]
I added errors and messages to all action classes similar to struct action errors and messages, we can check with hasErrors() and hasMessages() functions if so we can iterate over the list. I added errors.jsp and messages.jsp to show these. Next we need to include them in the jsp files where they are needed.

**Comment by adabutch** [comment]
alert messages have styles, closing.
