### ISSUE TITLE
FMLA Report

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#212]
Submitting an FMLA Report w.out a quarter selected returns this error.

Would be helpful if the error were more human-readable.

Would also be nice to return results for all quarters if none in-particular were chosen?

If not returning all is desired, we can disable submit button till required fields have their values.

<img width="758" alt="Screen Shot 2019-04-01 at 12 15 01 PM" src="https://user-images.githubusercontent.com/2372040/55342871-ce454b80-5477-11e9-942e-47424d683de6.png">

`page:` reportFmla.action

cc // @rbdietz print off

**Comment by sibow** [comment]
if quarter or year or start date not selected will show an error message about that
