### ISSUE TITLE
Job Title Updates

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#214]
**Dept:** ITS

**Jobs old/new:**

`System & Development Manager` **->** `Systems & Applications Manager`

`Web/User Interface Specialist`      **->** `Front-End Developer`

`Director Assistant`                          **->** `Assistant Director`

`System Administrator`                    **->** `Systems Administrator`

`Intern?` (is N. Myers?)

- - - 

@rbdietz requests the above job titles be updated. I'm not sure about _**officially**_ updating such, ping @charlesbrandt / @sibow.

**Comment by charlesbrandt** [comment]
I think these titles are being pulled from NWS. If so, we'll need to work with HR to affect the change. In this case, it may be best if the change request comes from Rick. Walid, could you confirm that NWS is the source of the titles?

**Comment by sibow** [comment]
Yes these match NW titles. So we need to ask HR to change these and timetrack subsequently will update
these.

**Comment by charlesbrandt** [comment]
Thanks for the clarifications. Since this is an internal configuration, I have started an email thread about it. It does not need to be tracked as part of Timetrack development.
