### ISSUE TITLE
Reason / Project attribute for Earn Codes

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#215]
Some departments needs to track an additional attribute to designate a reason for taking overtime. 

We do not want to clutter the earn code list with additional earn codes for each of the reasons. Associating the reason code as an additional attribute with the earn code should avoid this clutter.

**Comment by sibow** [comment]
I will be adding 4 earn codes, two related to monetary and two for comp time earned.
Each will have one to one hour and one to one and half matching. 
The suggested codes will be something like OTP1.0, OTP1.5, CEP1.0 and CEP1.5 and P stands for police 
and to be different from OT1.0, OT1.5, CE1.0 and CE1.5. these will have start time and end time 
values and map to OT1.0, OT1.5, CE1.0 and CE1.5 in new world script.

We will add a new parameter such Earn_code_reason to hold the reasons list that we are going to get 
from Elaine.

**Comment by sibow** [comment]
the new codes will be OTt.10, OTt1.5, CEt.10, CEt1.5 and OTSPt instead. I decided to use lower t to indicate time instead of letter P as we may use for other non police groups.

**Comment by sibow** [comment]
completed
