### ISSUE TITLE
Automated script for setting employee status

### ISSUE THREAD

**Issue by schertza** [City-of-Bloomington/timetrack#216]
We should consider what datapoints to use for automated scripting of the Timetrack employee status.

It appears that a configuration in ActiveDirectory can "overwrite" the employee Status recieved from Payroll system. This action can make it so a employee that is active in payroll but not in Active directory would become inactive in Timetrack.  Inactive timetrack employees are not exported to Payroll.

We should consider and define these points to insure that active employees can and will be paid regardless of there settings in active Directory. (my opinion)

Let us discuss, thank you,

alan

**Comment by charlesbrandt** [comment]
Thanks for raising the issue. Some of this gets into the discussion for intake and exit processes, which eventually should be mapped via the [account tracker project](https://github.com/City-of-Bloomington/account_tracker). 

In the meantime, I agree that if a user has hours for the current pay period, that should take priority over their 'active' status when it's time to export those hours.

**Comment by sibow** [comment]
implemented
