### ISSUE TITLE
Separate display for week1 and week2 earn code summary 

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#217]
<img width="1250" alt="Screen Shot 2019-04-08 at 11 09 35 AM" src="https://user-images.githubusercontent.com/2225624/55735726-e70dae00-59ef-11e9-8745-eb9b94e9b626.png">

On first glance, it can be difficult to tell which week the "Amount" column goes with. There is no divider between the week1 amount and the week2 earn code. It may be better to make these two separate tables so on mobile they could wrap one above the other. 

It would also be nice to make the "Amount" column automatically hide when no "Amount" values are present.

**Comment by charlesbrandt** [comment]
I just noticed that this layout has been cleaned up on the Time Details page. Ideally we can re-use that same layout.

**Comment by sibow** [comment]
I carried over the div's from approve page to timedetails page to fix this issue.
As far as removing amount column, we are going to lose consistency in the display especially on the approve pages where some employees may have amounts and others do not. Keeping it consistent will be nice.
