### ISSUE TITLE
Add/Edit Time Blocks

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#22]
These need love. 

Also, let's explore options for this without having to open in a new window.

<img width="404" alt="screen shot 2018-06-13 at 2 47 26 pm" src="https://user-images.githubusercontent.com/2372040/41371647-043c04da-6f19-11e8-9049-ab7813c8fb54.png">

**Comment by adabutch** [comment]
**before vs after:**

<img width="808" alt="add edit time block" src="https://user-images.githubusercontent.com/2372040/41481039-83386b58-709e-11e8-8671-93431b1540f6.png">

**Comment by adabutch** [comment]
AM/PM is being weird, using the same var ... will check tomorrow.

<img width="507" alt="screen shot 2018-06-21 at 4 54 44 pm" src="https://user-images.githubusercontent.com/2372040/41745230-49dd4a7e-7574-11e8-98b2-ae3db6f2e386.png">

**Comment by adabutch** [comment]
screenshot via commit [24ad5cd](https://github.com/City-of-Bloomington/timetrack/commit/24ad5cde0e1079b16e7ccb8d0521be8cc7c04555)

<img width="506" alt="screen shot 2018-06-22 at 9 01 19 am" src="https://user-images.githubusercontent.com/2372040/41778047-66e0148a-75fb-11e8-800e-c7283ed61808.png">

**Comment by rbdietz** [comment]
We might consider de-emphasizing: overnight, repeat and include.  I think
they should be included, but they will be used infrequently relative to the
other fields.  Not sure this is a good idea, just throwing it out.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by adabutch** [comment]
closing, we can address additional time block issues in new tickets when they arise.
