### ISSUE TITLE
Add unscheduled time off occurances to the time approval screen for AFSCME employees

### ISSUE THREAD

**Issue by schertza** [City-of-Bloomington/timetrack#227]
To my understanding Afscme employees are entitled to 6 unscheduled absences in a rolling year.

It might be helpful to do an historical review over the year to see how many instances of PTOUN and SBUUN (PTO unscheduled, Sick Bank Used unscheduled) have been used in the last year. Output could be similar to:

Unscheduled Time off: 1. 08/04/2018, 2. 09/23/2018, 3. 12/05/2019, 4. 03/12/2019

This implies that there were 4 occurrences of either PTOUN or SBUUN on the listed dates.

This output may be needed on both the time detail screen as well as the Time approval screen.

Note: this rolling count of 6 occurrences in a year is not stored in NWS.

**Comment by sibow** [comment]
Added when PTOUN (unscheduled PTO) and SBUUN (unscheduled sick) are used within one year of
the pay period, it will list the dates, earn code and hours
