### ISSUE TITLE
time clock

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#23]
**Time Clock first pass goal:**

Provide easy visual reference to the current time, date and their action (in/out).

Then we present the user with brief feedback related to their action. 

ie: 

```
Hi, Adam Butcher!

Current Time logged:
9:00 AM - 5:00 PM -- 8 hrs REG

```

![timeclock](https://user-images.githubusercontent.com/2372040/41977380-2acb4384-79ed-11e8-83b6-81dc7075f9e4.jpg)

**Comment by charlesbrandt** [comment]
I think the current timeclock interface is a great improvement. I'd prefer to separate any new changes or ideas in a different issue.

**Comment by adabutch** [comment]
Reopening for a few brief changes.

Mainly, the confirm screen needs to be a little shorter - as this will cause delay when multiple people are trying to use the interface in succession.

**Comment by rbdietz** [comment]
Some ideas for consideration, not directives...

Colors
Use color to show state....
Blue for ready, yellow for processing, green for successful entry, red for unsuccessful entry

Icons in Background?

Ready for input - Gears?
https://thenounproject.com/search/?q=gear
Processing (yellow bground)
Gears
Success - check box
https://thenounproject.com/search/?q=success
Fail - Circle slash of X
https://thenounproject.com/search/?q=fail

Text Scale
Large Text on state: Ready, Success ("Clocked in" "Clocked Out"), Fail

Questions:
Should card ID number be shown to users?

**Comment by charlesbrandt** [comment]
I typically associate gear icons with "settings" or "configuration". A ready state may be as simple as not showing success or fail.

**Comment by sibow** [comment]
for employees with multiple jobs we will have a second screen where employee's jobs will be listed and the employee must pick one of them. By default the primary job will be selected.

**Comment by adabutch** [comment]
I feel this issue is safe to be closed as we are now moving into a second iteration where users could potentially select from multiple jobs within the time clock interface as well as it handling `batch time ins`.

Other iterations can be separate issues too.
