### ISSUE TITLE
Add "as of date" to the "Accrual Summary" section of the Timedetail screen

### ISSUE THREAD

**Issue by schertza** [City-of-Bloomington/timetrack#249]
The timedetail screen normally references a given pay period. But the accrual Summary section sometimes (during the payroll week) refers back future than the current payperiod.  The usage of accruals (as well as the NWS balance) does sometimes reference dates early than the current payperiod.  

I'm suggesting listing the effective date on the Accrual Summary. The normally would be the firstday of a payperiod. But during the pay week it would reflect the first day of the previous pay period.

This date would hopefully remove confusion of the usage listed during the payroll week.

**Comment by sibow** [comment]
it is showing now on the accrual summary portion of time details tab
