### ISSUE TITLE
Holiday in the weekend is not showing

### ISSUE THREAD

**Issue by sibow** [City-of-Bloomington/timetrack#255]
For Fire they use Holiday pay for people who work on Sunday Easter 4/12 but it is not showing 
 on timedetail page, could be style related issue. But it allows for employee to add holiday pay 
on that day even though it is not showing

**Comment by adabutch** [comment]
After chat this morning, we have decided we may want to keep this as is.

**Comment by sibow** [comment]
I think it is still useful for supervisors who enter data for their employees to know if the day is a holiday or not
