### ISSUE TITLE
Calendar Time Entry Tab Focus

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/timetrack#257]
On Calendar view, the Time Entry popup should automatically provide focus on the TIME IN field with an active cursor, allowing time entry immediately upon opening the popup.

**Comment by adabutch** [comment]
@rbdietz - Is this the correct place? We should be expecting this focus behavior, but perhaps we do have an issue - however I'm not noticing an issue via Chrome/FF on Mac.

The blue outlined input in the screenshot below is focused for me on popup, with an active blinking cursor.

<img width="561" alt="Screen Shot 2020-05-29 at 1 27 03 PM" src="https://user-images.githubusercontent.com/2372040/83287764-37297000-a1b0-11ea-8b52-15972d63e541.png">

@sibow / @chenglan1 - do either of you see this, not focused as Rick mentioned?

Thanks everyone!

**Comment by chenglan1** [comment]
It focuses in the Time In box for me (Mac with Chrome). It did the same in Safari on my Mac, but it took a few seconds to get focused.

**Comment by sibow** [comment]
completed by Adam
