### ISSUE TITLE
Question regarding badge reader

### ISSUE THREAD

**Issue by sbayeta** [City-of-Bloomington/timetrack#276]
Hi guys! 
Really nice project 👌. I just went over the source trying to find out how you interface the badge reader, but couldn't find anything. Are you using the web serial api? Can you point me to some relevant code?
Thanks!

**Comment by inghamn** [comment]
The badge readers are connected to Raspberry Pis which submit the clock-in clock-out times via an HTTP web service call to Timetrack.

**Comment by schertza** [comment]
Hello sbayeta,

I interpreted your question as: how are we reading data from the serial card reader. We are taking advantage of the card reader being on the usb bus of the Pi. It is then just like a keyboard device where the data is coming in on sdtin. We did setup the card reader to append a carriage return on the end of the data stream when a card is read. This data is just submitted as Cliff described. I hope this answers your serial api question and why you could not find the code.

Thanks, alan

**Comment by sbayeta** [comment]
Thanks guys! I don't know why I assumed that the RPi was running a web client. 

Cheers!
Santiago
