### ISSUE TITLE
Time entry modal: default values after Hours Code selection

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#28]
When entering an hours block in timetrack, changing the Hours Code field will result in default values to be supplied to the Time in, Time out, or Hours fields (as applicable). 

If the Tab key is used to navigate to the fields, the default values will be selected and are easy to replace. If using a mouse, this behavior requires selecting the newly supplied defaults before adding the desired value. 

<img width="1140" alt="screen shot 2018-07-06 at 4 23 15 pm" src="https://user-images.githubusercontent.com/2225624/42398720-ebb98784-8138-11e8-951f-3130efe13a7c.png">

Related to #22.

**Comment by sibow** [comment]
the time out will default to empty for records that have clock in time only
