### ISSUE TITLE
calendar forward/backward controls

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#30]
<img width="178" alt="screen shot 2018-07-10 at 3 59 25 pm" src="https://user-images.githubusercontent.com/2372040/42534264-481bddfa-845a-11e8-8004-2588e725062d.png">

`<` should go backwards in time & `>` should go forward in time - per pay periods.

@sibow - I think I'll need your assistance? (when you get some free moments) thanks!

**Comment by sibow** [comment]
so this will advance one pay period relative to the current one, similarly we go back one pay period relative to current date.

**Comment by sibow** [comment]
implemented on timedetail, approve and payroll process pages and added appropriate links
