### ISSUE TITLE
Add visual indicator to distinguish Test environment from Production

### ISSUE THREAD

**Issue by gjoverto** [City-of-Bloomington/timetrack#305]
The interface and URL of Test and Production are difficult to tell apart so add a visual indicator, such as a banner to the Test environment that displays on all pages of the application. 

The standard adopted for New World and Enterprise Permitting & Licensing is a colored banner (blue = Production, green = Training, yellow = Test) with a text label of the environment.

Tyler Hub Test example:
![Screenshot 2024-08-05 at 10 17 04 AM](https://github.com/user-attachments/assets/bd9bc25f-e5d1-4af9-ae1b-93d6f6e521e8)

**Comment by sibow** [comment]
implemented, on test servers it will show Test Mode with yellow background
