### ISSUE TITLE
Commute Incentive Cap

### ISSUE THREAD

**Issue by gjoverto** [City-of-Bloomington/timetrack#308]
City policy caps an employee's commuter incentive earnings for the year at $500. Time Track correctly calculates and caps an employee's earnings for a single commuter incentive code at $500. However, if an employee reports more than one commuter incentive code, they can claim more than the $500 allowed. 

The function that prevents an employee from claiming more than $500 needs to use both commuter incentive codes in the calculation.

**Comment by sibow** [comment]
fixed and completed
