### ISSUE TITLE
Time Clock confirm screen

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#31]
The confirm screen needs to be a little shorter - as this will cause delay when multiple people are trying to use the interface in succession.

**Comment by charlesbrandt** [comment]
One other suggestion that I brought up with Walid and Alan is to allow the confirmation screen to accept another badge action input. This could be the same single text entry field that is on the initial main screen. Submitting the new badge would then update the confirmation screen with new details directly from the action. 

Walid should be able to help with rendering the correct form and targets server side for this action to work.

**Comment by adabutch** [comment]
@charlesbrandt - good thinking, I think this would be nice!

**Comment by charlesbrandt** [comment]
One potential downside of this would be the ability to accidentally take two actions in a row -- clock in and clock out. Would it make sense to prevent another action from the same badge ID if on the confirmation screen?

**Comment by charlesbrandt** [comment]
Yes, exactly. I think waiting for the main screen is a good prevention method for unwanted events for the same badge number.

**Comment by adabutch** [comment]
**Use Case (single job user(s)):**

**_batch process_:**
**- User One:** Swipes badge for clock-in submission action.
**- User One:** Presented with clocked-in confirmation screen.
**- User Two:** Swipes badge while confirmation screen of User One is still present.
**- User Two:** Presented with clocked-in confirmation screen.

**note:** Protection should be in place to stop a user from accidentally "reclocking" themselves. E.g. User One's ID should be rejected if a self-reswipe happens on their own confirmation screen.

cc // @sibow

**Comment by charlesbrandt** [comment]
After a discussion today, we're thinking that the system can always go back to the clock-in screen. The clock-in screen will support a result message from the previous action (e.g. "Hi/Bye [user]). After a certain amount of time, the message can clear and the current time can be shown. Thanks everyone for the good suggestions.

**Comment by charlesbrandt** [comment]
Issue #143 is related

**Comment by adabutch** [comment]
now after demoing this feature, closing this ticket till otherwise. 😄
