### ISSUE TITLE
Payroll Submission

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/timetrack#33]
I just submitting my hours, expecting there would be a confirmation step.  There should be a second step if there are warnings/errors.  For instance I don't have 40 hours in either week, but the submit button is now gone.  Users should be able to address warning errors before the "Submit" button disappears.   Or have the option to cancel/correct issues or acknowledge issues and submit anyway.

Another issue is that if I go back to change/correct hours after I've submitted, I should have to resubmit so there is a record that I have approved those changes and submitted them for approval up the chain.

**Comment by rbdietz** [comment]
It might be nice to see the relevant warning and errors in the interfaces, not just after hitting the submit button.

**Comment by adabutch** [comment]
Yes - this is pretty major, I feel. Will look into this next.

Thanks for the attention here @rbdietz

**Comment by adabutch** [comment]
GIF via [e379b6e](https://github.com/City-of-Bloomington/timetrack/commit/e379b6eb6a9432e3a26d7422bc5c0e7be49c27be)

![out](https://user-images.githubusercontent.com/2372040/42710421-f3212c60-86b1-11e8-966c-612aec3fe694.gif)

**Comment by charlesbrandt** [comment]
Is this using a server side call to check for errors, or is the error validation happening all client side? Some of the error checking code can be tricky, and it may be difficulty to synchronize that logic on both front and back ends. 

If the current iteration is all client side, @sibow is it possible to expose a server api call that will report any errors for the current timesheet?

**Comment by sibow** [comment]
The warning will show now even before submitting, when hours are less than 40 per week for example.
Submission means it ready for approve but does not mean can not be updated as needed by the user till it is approved then the user can not change anymore.
We have all the records that the users enters or updates, except we do not show the history, but can be shown if we have to for example under setting if we want to audit certain user and his/her time entries.

If the approver edits a record it will be marked as the approver did the change in the logs. So this can be part of the audit feature.

If we implement multiple submission, that we are going to ignore all the previous submission and go with the last one. I do not think it will add any value to workflow.

Let me know your ideas on this.
