### ISSUE TITLE
Entered time won't display correctly at first

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/timetrack#35]
After hitting the "Confirm" button when entering time there is an issue with time showing up. 

On Firefox, I get the prompt to Resend the data to display the page. "To display this page, Firefox must send information that will repeat any action (such as a search or order confirmation) that was performed earlier"  After I hit Resend, it takes me to a blank Block Time entry screen (timeBlock.action) that fills up the whole screen. I have to go back to load the Time Details page.

On Chrome,  I stay on the TIme Details page, but the time doesn't show up. Refreshing the page or moving to a new page and back to the Time Details doesn't do anything. I have to log out and back in to see it.

It may have to do with my privacy settings. I've allowed cookies. Maybe I need to do something else.

**Comment by sibow** [comment]
it is fixed

**Comment by adabutch** [comment]
fixed via issue #39
