### ISSUE TITLE
Modal time entry not submittable with keyboard

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/timetrack#38]
You cannot submit the form using the keyboard. I really hate having to grab the mouse between filling out the form and hitting submit.

It would be nice to be able to either hit "Enter" while one a form field (browsers' default action).  Or, if need be, tab through to the submit button and activate it with the spacebar.

**Comment by rbdietz** [comment]
This is important for accessibility reasons as well.

**Comment by adabutch** [comment]
This should be patched up (till & if we break up for the form(s) as discussed this morning).

Closing for now, happy to reopen if need be.
