### ISSUE TITLE
Modal time entry form redirects to timeblock.action

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/timetrack#39]
Instead of submitting and refreshing the current calendar display, the browser redirects to /timetrack/timeblock.action
![a](https://user-images.githubusercontent.com/630282/42779525-b4eb637a-890e-11e8-8dda-9a16f4f262bc.png)
![b](https://user-images.githubusercontent.com/630282/42779526-b4fca55e-890e-11e8-9913-6a226ff5019e.png)
![c](https://user-images.githubusercontent.com/630282/42779528-b50ca36e-890e-11e8-8819-4c256ce2ba41.png)

**Comment by adabutch** [comment]
This should be fixed, closing. 

We can reopen later if the issue resurfaces.
