### ISSUE TITLE
Second part of time range always shows up as AM

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#42]
I'm guessing this is a quick fix, but the second part of the the time block shows up as AM regardless of being AM or PM. The underlying value appears to be correct since the total hours are calculated correctly. 
<img width="153" alt="screen shot 2018-07-18 at 9 08 49 am" src="https://user-images.githubusercontent.com/2225624/42883761-89511f22-8a6a-11e8-8316-7ce63e98510b.png">

**Comment by adabutch** [comment]
@sibow - 

We've seen this once before & you were able to fix it. 

Not sure why it's returned, could you check it out?

**Comment by sibow** [comment]
fixed
