### ISSUE TITLE
Repeat Amount confusing

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#43]
We've received feedback that the Repeat Amount field is confusing... does it include today? Currently, the repeat amount value is added in addition to today. It may be more clear and intuitive to include a date field for a "Repeat through" value. 
<img width="577" alt="screen shot 2018-07-18 at 9 23 17 am" src="https://user-images.githubusercontent.com/2225624/42884459-62774690-8a6c-11e8-9e4e-de9272318f7b.png">

**Comment by adabutch** [comment]
@sibow - Thoughts on this one?

@charlesbrandt - Do you have a feeling one way or the other on the direction this should go?

**note:** Kuali features date range, with date selectors.

**Comment by rbdietz** [comment]
Can we determine from Kuali usage how many people use the functionality at
all?  We might want to hide or further minimize tis if its low.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
I'm not sure how we would quantify use within the Kuali app (maybe @sibow has a way to analyze logs), but there was at least one user just in ITS who was trying to use the function. For employees who keep very regular schedule it could be useful.

**Comment by sibow** [comment]
The repeat count is addition to today, In Kuali they do not keep track of the repeat records, they just enter the same record the number of times with different date. One way to figure out is to run a database query and find all the records that were entered on the same day and same time for every user. 
We can change it to start date, end date instead if everybody agree on that. 
At the time I thought entering a a digit is easier than picking a date range, even though there is substantial amount of code behind it considering having a weekend in the middle of repeat count.

**Comment by sibow** [comment]
in the new release, it is changed to date range, start date and end date instead. We will still have 'include weekend' flag if the date range will cover some or all weekend dates.

**Comment by sibow** [comment]
it is not relevant any more as it is changed to date range.
