### ISSUE TITLE
Errors fail silently

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#44]
In previous iterations, error messages were shown in the separate pop-up window that was opened to handle time entry. This created confusion on when actions were complete. 

We've moved on to a modal dialog model which has improved the user experience for time entry. However, one thing that we've lost is any type of messaging to show when an error occurs. I don't think we want to duplicate all of the error checking code on the client side. 

That means the server needs a way to signal to users when an error occurred after the modal dialog has already closed. In Django, that is possible using [one-time notification message (also known as “flash message”)](https://docs.djangoproject.com/en/2.0/ref/contrib/messages/). What would be involved with implementing something similar here?

**Comment by adabutch** [comment]
@sibow -

I have an alert element in the time block modal dialog that is ready to be populated with any errors that might occur upon submitting/"confirm"'ing.

For example, if I submit conflicting times for the same day:  the alert element in the modal dialog should be populated with the returned error (and I think the modal should remain open during this, so the user can hopefully correct and resubmit for a successful time block submission).

This relates to some client "band-aid" checking I'm doing which can be removed once this is in place ... follows @charlesbrandt comment [here](https://github.com/City-of-Bloomington/timetrack/issues/33#issuecomment-404947942) & my GIF right above his comment.
