### ISSUE TITLE
Eligible for holiday pay verification check

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#45]
At the City of Bloomington, to be eligible for holiday pay, you must work the day before and after the holiday or use paid benefit time such as PTO and/or comp time. Unpaid authorized time before and after a holiday results in a loss of holiday pay. 

Timewarp should check for this condition up front and prevent adding holiday pay in this condition.

**Comment by sibow** [comment]
in kuali we can not prevent this but we can issue a warning, in timetrack we should be able to prevent it unless if we do not have what will be after or before if not entered yet.

**Comment by sibow** [comment]
According to Kelly, if the day or the day  after is authorized unpaid leave then no holiday pay is allowed. One day not necessarily the two days.
