### ISSUE TITLE
Add time entry redirects to current pay period

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/timetrack#46]
When adding time entries for last pay period, submitting the time block redirects to the current pay period, instead of remaining on the pay period I was working on.

Submitting a new time entry should redirect you back to the pay period of the submitted time entry.

**Comment by sibow** [comment]
It is not happening for me, I even went back tow pay periods and still was able to change or delete and the page staid on the same pay period. I used firefox.

**Comment by sibow** [comment]
I think this is fixed

**Comment by inghamn** [comment]
This is still not fixed

**Comment by adabutch** [comment]
this should be fixed now, closing.
