### ISSUE TITLE
Missing indication of current timesheet owner during approval

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#48]
After clicking on a person's name to see the details of their timesheet, there is no indication of whose timesheet the approver is looking at. 

For example, I am looking at Adam's timesheet here:

<img width="1140" alt="screen shot 2018-07-30 at 10 01 01 am" src="https://user-images.githubusercontent.com/2225624/43402105-e2f31b4c-93df-11e8-9091-da32281ef813.png">

The equivalent screen in Kuali Time gives a clear indication of the proxy behavior: 
<img width="1303" alt="screen shot 2018-07-30 at 10 06 37 am" src="https://user-images.githubusercontent.com/2225624/43402249-4d58b546-93e0-11e8-8907-89b58236dec8.png">

**Comment by sibow** [comment]
it is fixed but not in production yet
