### ISSUE TITLE
Make the day on the calendar clickable

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#5]
Currently, for the time entry, the user must click on the date number in the calendar field. Ideally, it should be possible to click anywhere on the day in order to bring up the time entry field. I think this should be possible with css:

th_text {
    display: block;
    width: 100%;
    height: 100%;
}

**Comment by sibow** [comment]
this suggestion did not work and caused the page layout distorted. Still looking for a good css to do the trick.

**Comment by adabutch** [comment]
@charlesbrandt / @sibow - I believe this should be, and is, solved via issue #13 ... 😄

**Comment by charlesbrandt** [comment]
Looks good to me!
