### ISSUE TITLE
Today

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/timetrack#51]
We might want some visual indication of which date is Today in the calendar view.  Perhaps a background color or border difference for emphasis.

**Comment by charlesbrandt** [comment]
I'm not seeing this one on outlaw.

Not sure about the exact styling, but something like this may be what is being requested:
```
<div class="day today" data-block-id="" data-doc-id="266" data-date="08/16/2018" data-order-index="3" style="border: blueviolet;border-width: 2px;border-style: solid;">
      </div>
```

<img width="1140" alt="screen shot 2018-08-16 at 8 45 28 am" src="https://user-images.githubusercontent.com/2225624/44209202-c1febf00-a130-11e8-96d3-291dc68a01cd.png">

**Comment by adabutch** [comment]
@charlesbrandt the class is there, just not the style ... coming today!

**Comment by adabutch** [comment]
<img width="1163" alt="screen shot 2018-08-16 at 12 38 02 pm" src="https://user-images.githubusercontent.com/2372040/44222068-6bee4380-a151-11e8-8e63-36c3e4ad9c16.png">


gave today the hover state colorway, happy to adjust as we see fit ... but the functionality is all in place, so changes are easy! 😄

**Comment by rbdietz** [comment]
How about same hue, but lighter than the hover state.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov
