### ISSUE TITLE
Indicate timesheet has been submitted

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#54]
On a new timesheet there are buttons for adding a note or submitting the timesheet:

<img width="1140" alt="screen shot 2018-08-13 at 9 49 25 am" src="https://user-images.githubusercontent.com/2225624/44036489-e450cefc-9edf-11e8-8567-1ebf18430dd1.png">

After the timesheet has been submitted, those buttons disappear. 

It is possible to confirm the submission by looking in the collapsed "Action History" section, but it might be better to provide some indication where the submit buttons were that says: 

    Submitted on: [datetime]

**Comment by adabutch** [comment]
cc // @sibow - left your name in the static text for this change

**Comment by sibow** [comment]
after submission the submission date and time will show up instead.
