### ISSUE TITLE
Indicate both submit status and approval status on Payroll Processor page

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#57]
It would be useful as a Payroll Processor to know if the "Not Approved" status is showing because a user has not submitted their timesheet, or if it has not been approved by the manager:

<img width="1140" alt="screen shot 2018-08-13 at 4 55 58 pm" src="https://user-images.githubusercontent.com/2225624/44058180-58e5d04c-9f1b-11e8-9bf1-092009b9bdd8.png">

Could we add the submit status of the timesheet in addition to the approval status? Once it has been approved by the manager, it's fine to leave it as only "Payroll Process Approve"

**Comment by rbdietz** [comment]
Perhaps a red block for [not submitted]?






Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by adabutch** [comment]
^^ sure! @rbdietz / @charlesbrandt - how would you like these colored?

<img width="392" alt="screen shot 2018-08-14 at 12 59 19 pm" src="https://user-images.githubusercontent.com/2372040/44106185-ea92f8e8-9fc1-11e8-8c64-561377c1257c.png">

**Comment by rbdietz** [comment]
Here's what I'm thinking...

Red for "Time not submitted"
Orange for "Time not approved"
Yellow for "Payroll not submitted" 
Green for "Payroll Approved"
Blue for  "[ ] Approve Payroll" and "[ ] Select All"

**Comment by adabutch** [comment]
@rbdietz - commit above should do it (note: when timetrack is sync'd with outlaw next).
