### ISSUE TITLE
Proxy Visability

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/timetrack#58]
When operating as a proxy users, there needs to be very high visibility for this... like a change of background color to red, big red banner, or something like this.  Right now it is virtually impossible to tell that you are in proxy mode or on whose behalf.

Also System needs to log events/changes to information by a proxy.

**Comment by adabutch** [comment]
@rbdietz - this (below) style is in outlaw only at the moment, should be available next timetrack release.

<img width="1344" alt="screen shot 2018-08-14 at 1 03 39 pm" src="https://user-images.githubusercontent.com/2372040/44106415-97d38c0c-9fc2-11e8-874e-33577900312e.png">

**Comment by adabutch** [comment]
cc // @sibow - note: needs log events/changes to information by a proxy.

**Comment by sibow** [comment]
it is already implemented, all proxy actions are logged, you can check the logs link in the bottom of the page.
