### ISSUE TITLE
Consider different color for non-regular hours blocks

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#59]
Currently all timeblocks are rendered the same way. The earn code is displayed, but it can be easy to miss when scanning a time sheet. 

We should consider rendering any block that is not a Regular Hours block differently. Non-regular hours blocks should stand out a bit more, since they are usually an exception. All non-regular timeblocks can be rendered in the same way. I don't think we want to try to assign a different look for each different type. 

<img width="1140" alt="screen shot 2018-08-14 at 1 28 06 pm" src="https://user-images.githubusercontent.com/2225624/44107878-b8e4b2e6-9fc6-11e8-80c8-e900a1e7a529.png">

**Comment by adabutch** [comment]
non-regular blocks now as below, happy to change as we desire down the road

<img width="220" alt="screen shot 2018-08-14 at 4 00 44 pm" src="https://user-images.githubusercontent.com/2372040/44115190-373f7ef0-9fdb-11e8-9d5b-150bd6bdd094.png">

**Comment by rbdietz** [comment]
I'm not sure about the yellow here.  It's too attention grabbing perhaps.
 Maybe something like this?






Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by adabutch** [comment]
@rbdietz - ^^ attach the pic again

**Comment by rbdietz** [comment]
![screen shot 2018-08-14 at 4 15 20 pm](https://user-images.githubusercontent.com/1135994/44128996-1000fa1a-a014-11e8-8e68-50e85d40aeb2.png)

**Comment by adabutch** [comment]
Non-regular timeblock hours are showing with, `#d1d1c5`
