### ISSUE TITLE
approve/process batch user list view

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#60]
Note: 

via Rick's drawing ... near the top of the approval/payroll process pages, let's display a batch users list via "not submitted," and "not approved" piggy-back'ing status indicators currently setup for color-coding.

Eventually, we will want an email feature tied to this where these grouped users can easily be emailed by a click.

**Comment by adabutch** [comment]
@rbdietz / @charlesbrandt - thoughts? thanks!

<img width="1135" alt="screen shot 2018-08-15 at 9 22 50 am" src="https://user-images.githubusercontent.com/2372040/44150283-e74a4c80-a06c-11e8-95df-493b81147067.png">

**Comment by rbdietz** [comment]
This looks great, but you might consider dropping the "Select all"
underneath this block and an <hr> and aligning it to the right so it's part
of the approval action area.  This block is just informative.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by adabutch** [comment]
<img width="1151" alt="screen shot 2018-08-15 at 11 08 27 am" src="https://user-images.githubusercontent.com/2372040/44155572-a87256b0-a07b-11e8-8f84-309069b88e46.png">
 ^^ @rbdietz

**Comment by rbdietz** [comment]
Thanks, looks good.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by sibow** [comment]
completed
