### ISSUE TITLE
approval/process per user period dates

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#62]
Show pay period ranges for each user next to the week 1 / 2 text.

**Comment by adabutch** [comment]
@rbdietz - 

<img width="1144" alt="screen shot 2018-08-15 at 10 07 09 am" src="https://user-images.githubusercontent.com/2372040/44152260-0fd5b058-a073-11e8-8d33-d015ad7d1aa4.png">

@sibow - we need pay period dates separated in the same manner as seen in the above screenshot.

ie.
Week 1 - **_(date - date)_**
Week 2 - **_(date - date)_**

**Comment by charlesbrandt** [comment]
Quick heads up... it doesn't look like these are being derived from the selected pay period on outlaw:

<img width="1140" alt="screen shot 2018-08-16 at 8 59 59 am" src="https://user-images.githubusercontent.com/2225624/44209926-e3f94100-a132-11e8-9abe-73b6bef8d84f.png">

**Comment by adabutch** [comment]
@charlesbrandt - this is static, Walid will provide these dates soon

**Comment by sibow** [comment]
added this feature
