### ISSUE TITLE
Allow the creation of a 'Clock IN' entry via web interface

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#64]
When using the web interface to create a new time block, both 'Time in' and 'Time out' values must be specified in the form in order for a new block to be created. 

<img width="1140" alt="screen shot 2018-08-15 at 1 20 36 pm" src="https://user-images.githubusercontent.com/2225624/44162470-6bd93f80-a08e-11e8-9ff2-28f8a8c69160.png">

However, when using the timeclock interface, a block with only a Clock IN entry is created:
<img width="1140" alt="screen shot 2018-08-15 at 1 19 05 pm" src="https://user-images.githubusercontent.com/2225624/44162639-e4400080-a08e-11e8-9bd0-9ef3c461487c.png">

It is even possible to edit the Clock IN block via the web interface. 

It would be nice if a similar option was possible via the web form. If only a Time in value is specified, the system would create a Clock IN entry. This would allow employees who miss a clock in to alert their managers. Managers could create the clock in event and then employees could clock out as expected.

**Comment by sibow** [comment]
implemented, the user can enter clock in time only and the managers can edit the clock-in time for their employees without adding time out entry

**Comment by charlesbrandt** [comment]
I'm still not able to create a new Clock IN entry (no clock out) via the web interface.

**Comment by sibow** [comment]
it is fixed now.

**Comment by adabutch** [comment]
<img width="515" alt="screen shot 2018-11-14 at 8 48 53 am" src="https://user-images.githubusercontent.com/2372040/48487765-2c390580-e7ed-11e8-8bc8-ac006d3021b1.png">

@sibow We need `clock in` only ability here on the time block. Please & thanks!

**Comment by charlesbrandt** [comment]
This is working in the current version on production.
