### ISSUE TITLE
Increase the size for approval checkbox

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/timetrack#67]
We've received feedback that the size of the checkbox for different Approval actions is too small. Could we try bumping that up a bit?

**Comment by charlesbrandt** [comment]
<img width="1140" alt="screen shot 2018-08-16 at 8 52 35 am" src="https://user-images.githubusercontent.com/2225624/44209614-0048ae00-a132-11e8-8dba-c1a41bd1bed1.png">

Yeah, and also the approve options. We may want to consider a way to maintain the "Approve All" functionality (current) and also add in an "Approve one" without clicking the individual checkbox and the scrolling down to the bottom to hit the approve button. Maybe include an Approve button next to the check box? Happy to discuss more...

**Comment by rbdietz** [comment]
We might want to use the area between <hr>'s for the select all also for
"notify staff with time not submitted" (red), "notify approvers" buttons
(orange).





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov
