### ISSUE TITLE
approve/process notify functionality

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#68]
<img width="1138" alt="screen shot 2018-08-16 at 10 10 18 am" src="https://user-images.githubusercontent.com/2372040/44213839-aac5ce80-a13c-11e8-8c29-e1a23c2ca39a.png">

> We might want to use the area between `<hr>'s` for the select all also for "notify staff with time not submitted" (red), "notify approvers" buttons (orange).

- Rick Dietz

**Comment by rbdietz** [comment]
This could be an "Actions:" area





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
For the notification message templates, something like the following may be appropriate:

```
Subject: Timesheet Reminder

Quick reminder: Please submit your timesheet for the last pay period when you have a moment. The Timetrack system is available here:

https://timetrack.bloomington.in.gov

```
Similarly, the approval notification message could be:

```
Subject: Timesheet Approval Reminder

Quick reminder: When you have a moment, please review and approve time sheets for your direct reports for the last pay period . The Timetrack system is available here:

https://timetrack.bloomington.in.gov
```

Suggestions are welcome

**Comment by charlesbrandt** [comment]
We may want to consider sending the email on behalf of the person who is submitting the 'send reminder' request. This way any replies will go back to the requestor. This is useful for replies stating that the action is complete. 

Similarly, it would be useful to automatically notify the requestor once the requested action has been completed by everyone who was notified. (e.g. all timesheets have been submitted by your team). This way the approver can take action as soon as possible, without manually polling for changes.

**Comment by sibow** [comment]
I need one for employees who did not enter their times for the pay period.

**Comment by sibow** [comment]
The approvers and payroll processors will have a link to remind employees or approvers that they need to submit or approve the employees

**Comment by sibow** [comment]
it is fixed in the new release.
