### ISSUE TITLE
Values outside normal range can be entered in time blocks

### ISSUE THREAD

**Issue by sethCOB** [City-of-Bloomington/timetrack#7]
When Overnight Shift is checked, values outside of the normal 00:00-24:00 range can be entered, including negative values.

![image](https://user-images.githubusercontent.com/31547590/35529733-f7f2b7c4-04ff-11e8-9b3a-e610a7297db1.png)

![image](https://user-images.githubusercontent.com/31547590/35529747-fe51416c-04ff-11e8-8ce8-4ef9cb4d4c87.png)

**Comment by sibow** [comment]
modified to not accept negative values and put max limit to 36 hrs for overnight workers such as firefighters
