### ISSUE TITLE
Issue with partial time blocks

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/timetrack#73]
If there is a partial time block.  I should be able to click on that block to edit it further.  Likewise I should be able to click on the calendar day (outside the partial time block) to create a new non-overlapping time block.  Currently no matter where I click on the day it opens the partial timeblock for editing.

**Comment by adabutch** [comment]
I'm not sure this is an issue any longer after closing #74 ?

**Comment by rbdietz** [comment]
I think this fixed the problem.  Thanks.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by adabutch** [comment]
Thanks! closing
