### ISSUE TITLE
Time editing dialog

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/timetrack#74]
If had a couple of incidents when I open a time-block for editing or a new time-block.  If I enter starttime but don't save it, and then click outside to close it, if I click a different day or some day the edit dialog comes up with the entered number not a blank field.

**Comment by adabutch** [comment]
![out](https://user-images.githubusercontent.com/2372040/44728380-5d395200-aaaa-11e8-9713-649b8e23312d.gif)

**Comment by adabutch** [comment]
i think this does it here
