### ISSUE TITLE
Payroll Approver Information

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/timetrack#75]
For each staff member it would be helpful to include the same information on accruals and hours requirements as we have in timewarp.  

![screen shot 2018-08-28 at 11 01 06 am](https://user-images.githubusercontent.com/1135994/44733613-f1f57d00-aab5-11e8-900c-83af88da4b3d.png)

**Comment by adabutch** [comment]
@sibow - if you can provide me with the data for this, I can incorporate.

**Comment by sibow** [comment]
added
