### ISSUE TITLE
Accrual Info Missing

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/timetrack#76]
The for the most recent pay period, accrual information is missing on my hours entry page.

Accrual Summary
Note: Accrual / Benefits information is not yet available for this pay period.

**Comment by charlesbrandt** [comment]
I'm guessing that the information is considered out of date and has not been synchronized from New World. Walid can confirm.

**Comment by rbdietz** [comment]
I assume that information needs to be there to accurately render errors and
warnings correct?  Please update this asap.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by charlesbrandt** [comment]
Walid found the source of this to be his import script and fixed that. It was only occurring for people who are in two groups. I believe that's only department heads.
