### ISSUE TITLE
oncall35 for utility employees

### ISSUE THREAD

**Issue by sibow** [City-of-Bloomington/timetrack#87]
Need to add u to OnCall35 for utility employees when exporting to new world

**Comment by schertza** [comment]
Additionally to the "Oncall35", the city of Bloomington needs to add a u to all hour_codes in TimeTrack's Timewarp export for employees in the Utilities department.

So each hour_codes for Utilities employees would use the u version of the code in our payroll system.

reg -> ureg

Alternatively we could configure additional earn_codes and only allow them to be used by Utilities deparment via hour_code restrictions.

**Comment by sibow** [comment]
it is updated, waiting for Kelly to test the output

**Comment by sibow** [comment]
Kelly tested it and said it is working
