### ISSUE TITLE
Prevent deselection of Employee ID input on badge workflow

### ISSUE THREAD

**Issue by sethCOB** [City-of-Bloomington/timetrack#9]
On timeClock.action, the Employee ID field (emp_id_code) can be deselected and requires the user to reselect the field before they can swipe their badge.

The following script can prevent this from happening:

```
<script>
var inputElement = document.getElementById("emp_id_code");
inputElement.focus();
inputElement.addEventListener("blur", function(event){inputElement.focus();}); 
</script>
```

**Comment by sibow** [comment]
updated, thanks for the suggestion
