### ISSUE TITLE
punch clock employee submit for approval issue

### ISSUE THREAD

**Issue by sibow** [City-of-Bloomington/timetrack#91]
Since punch clock employees will not be able to edit their timesheet now we have an issue, who will submit for them, their managers or automated process?

**Comment by sibow** [comment]
Now if they login, they can submit, or their supervisor (approver) can submit, we have a script for auto submit but it is not running right now till we decide if we really need this.

**Comment by rbdietz** [comment]
Clock entry users need to be able to submit/approve their hours AND add "Pay Period Notes".
