### ISSUE TITLE
styling new additions

### ISSUE THREAD

**Issue by sibow** [City-of-Bloomington/timetrack#93]
In order to be simple to find the new additions, I am listing them here so that Adam can easily find them if he decide to style them:

- [x]  1 - Timesheet Review link, it is similar to 'Timesheet Approval' page with less complications
- [x]  2 - Time Entry History link in the bottom of the TimeDetails page, and the related Time Entry History page
- [x]  3 - Approve page, More Details link in top
- [x]  4 - Approve page, Remind Employees link, will show after the list of non-submit employees list
- [x]  5 - Payroll Approve page, similar links to Approve page above.
- [x]  6 - timeDetailView page, get to it from review page when click on employee name.

**Comment by adabutch** [comment]
note: # (6) ... we might need to adjust this proxy background color as it's sometimes hard to see.
