### ISSUE TITLE
Weekly total decimal

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/timetrack#95]
Need to limit the decimal places shown in the weekly hour count tables.

**Comment by sibow** [comment]
this is fixed

**Comment by charlesbrandt** [comment]
I'm continuing to see this issue show up. 
<img width="1303" alt="screen shot 2018-10-26 at 1 34 26 pm" src="https://user-images.githubusercontent.com/2225624/47583081-569d4e80-d924-11e8-888e-640a1e086f71.png">

Is it possible to apply this filter every place that a decimal value is used? 

(also related to #71)

**Comment by rbdietz** [comment]
Yes to this.  There is rarely or never a case in this system where more
than 2 decimal place are needed.




Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by sibow** [comment]
this is fixed to use two decimals only
