### ISSUE TITLE
URL in "emailed reminders" contain a url with who's server name is not name served on the Internet

### ISSUE THREAD

**Issue by schertza** [City-of-Bloomington/timetrack#99]
I realize this issue is specific to the City of Bloomington's network.

to my understanding the email contains  the url similar to timetrack.bloomington.in.gov/timetrack 

I believe the Internet accessible (name served) url should be bloomington.in.gov/timetrack

I realize this is unique to city of blommington and our proxy server, but I just wanted to let everyone know the email reminder's embedded url are not working if the user is not on our local network. 

Thank you,

**Comment by sibow** [comment]
fixed

**Comment by charlesbrandt** [comment]
This issue is still happening as of Nov 19.

**Comment by charlesbrandt** [comment]
Just confirming that this was fixed and the email reminder that went out today contains the correct URL. Thank you!
